### ISSUE TITLE
豆瓣刮削bug

### ISSUE THREAD

**Issue by chris6868** [hsuyelin/nas-tools#10]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 刮削影视信息时无法刮削演员信息，查看日志显示“2023-07-24 13:20:05,421 INFO: 【Scraper】正在生成电影NFO文件：寻梦环游记 (2017) - 1080p
2023-07-24 13:20:22,036 INFO: 【Scraper】豆瓣该影片或剧集无演员 Polo Rojas 信息
2023-07-24 13:20:22,849 INFO: 【Scraper】豆瓣该影片或剧集无演员 Montse Hernandez 信息
2023-07-24 13:20:26,462 INFO: 【Scraper】豆瓣该影片或剧集无演员 Antonio Sol 信息
2023-07-24 13:20:27,258 INFO: 【Scraper】豆瓣该影片或剧集无演员 Liliana Barba Meinecke 信息
2023-07-24 13:20:28,054 INFO: 【Scraper】豆瓣该影片或剧集无演员 Emmanuel Bernal 信息
2023-07-24 13:20:28,866 INFO: 【Scraper】豆瓣该影片或剧集无演员 David Berón 信息
2023-07-24 13:20:29,664 INFO: 【Scraper】豆瓣该影片或剧集无演员 Denise Blasor 信息
2023-07-24 13:20:30,472 INFO: 【Scraper】豆瓣该影片或剧集无演员 Wilma Bonet 信息
2023-07-24 13:20:31,304 INFO: 【Scraper】豆瓣该影片或剧集无演员 Alex Castillo 信息
2023-07-24 13:20:32,139 INFO: 【Scraper】豆瓣该影片或剧集无演员 Vicki Davis 信息
2023-07-24 13:20:32,916 INFO: 【Scraper】豆瓣该影片或剧集无演员 Roberto Donati 信息
2023-07-24 13:20:33,733 INFO: 【Scraper】豆瓣该影片或剧集无演员 Efrain Figueroa 信息
2023-07-24 13:20:34,528 INFO: 【Scraper】豆瓣该影片或剧集无演员 Deb Fink 信息
2023-07-24 13:20:35,344 INFO: 【Scraper】豆瓣该影片或剧集无演员 Libertad García Fonzi 信息
2023-07-24 13:20:36,160 INFO: 【Scraper】豆瓣该影片或剧集无演员 Emilio Fuentes 信息
2023-07-24 13:20:36,969 INFO: 【Scraper】豆瓣该影片或剧集无演员 Daniella Garcia-Lorido 信息”

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues

**Comment by chris6868** [comment]
2023-07-24 13:31:54,049 INFO: 【Meta】385687 查询结果：速度与激情10
2023-07-24 13:32:10,212 INFO: 【Scraper】正在生成电影NFO文件：Fast.X.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG
2023-07-24 13:32:26,736 INFO: 【Scraper】豆瓣该影片或剧集无演员 Joaquim de Almeida 信息
2023-07-24 13:32:29,091 INFO: 【Scraper】豆瓣该影片或剧集无演员 Jaz Hutchins 信息
2023-07-24 13:32:29,878 INFO: 【Scraper】豆瓣该影片或剧集无演员 Luka Hays 信息
2023-07-24 13:32:30,655 INFO: 【Scraper】豆瓣该影片或剧集无演员 Alexander Capon 信息
2023-07-24 13:32:32,232 INFO: 【Scraper】豆瓣该影片或剧集无演员 Shadrach Agozino 信息
2023-07-24 13:32:33,012 INFO: 【Scraper】豆瓣该影片或剧集无演员 Ludmilla 信息
2023-07-24 13:32:35,380 INFO: 【Scraper】豆瓣该影片或剧集无演员 Michael Irby 信息
2023-07-24 13:32:36,151 INFO: 【Scraper】豆瓣该影片或剧集无演员 Shahir Figueira 信息
2023-07-24 13:32:36,937 INFO: 【Scraper】豆瓣该影片或剧集无演员 Ben-Hur Santos 信息
2023-07-24 13:32:37,759 INFO: 【Scraper】豆瓣该影片或剧集无演员 Debby Ryan 信息
2023-07-24 13:32:38,539 INFO: 【Scraper】豆瓣该影片或剧集无演员 Josh Dun 信息
2023-07-24 13:32:40,455 INFO: 【Scraper】正在保存NFO文件：/mnt/nas/media/downloads/video/Fast.X.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.nfo
2023-07-24 13:32:40,458 INFO: 【Scraper】NFO文件已保存：/mnt/nas/media/downloads/video/Fast.X.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.nfo
2023-07-24 13:32:40,458 INFO: 【Scraper】正在下载poster图片：https://image.tmdb.org/t/p/original/7BOzdJavykpnCZ5oTYvmtTTbK9O.jpg ...
2023-07-24 13:32:43,981 INFO: 【Scraper】poster图片已保存：/mnt/nas/media/downloads/video/poster.jpg
2023-07-24 13:32:44,743 INFO: 【Scraper】正在下载fanart图片：http://assets.fanart.tv/fanart/movies/385687/moviethumb/fast-x-6432db18cbcf6.jpg ...
2023-07-24 13:32:46,398 WARNING: , 3 秒后重试 ...
2023-07-24 13:32:49,400 INFO: 【Scraper】正在下载fanart图片：http://assets.fanart.tv/fanart/movies/385687/moviethumb/fast-x-6432db18cbcf6.jpg ...
2023-07-24 13:32:49,960 WARNING: , 6 秒后重试 ...
2023-07-24 13:32:55,966 INFO: 【Scraper】正在下载fanart图片：http://assets.fanart.tv/fanart/movies/385687/moviethumb/fast-x-6432db18cbcf6.jpg ...

Exception: 
Callstack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
2023-07-24 13:32:56,652 INFO: 【Scraper】/mnt/nas/media/downloads/video/Fast.X.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG.mkv 刮削完成
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-tools/app/utils/http_utils.py", line 113, in get_res
    return requests.get(url,
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-tools/app/media/scraper.py", line 411, in __save_image
    r = RequestUtils().get_res(url=url, raise_exception=True)
  File "/nas-tools/app/utils/http_utils.py", line 123, in get_res
    raise requests.exceptions.RequestException
requests.exceptions.RequestException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-tools/app/media/scraper.py", line 501, in gen_scraper_files
    self.__save_image(backdrop_image, dir_path, "fanart", force_pic)
  File "/nas-tools/app/utils/commons.py", line 56, in f_retry
    return f(*args, **kwargs)
  File "/nas-tools/app/media/scraper.py", line 423, in __save_image
    raise RequestException
requests.exceptions.RequestException

**Comment by hsuyelin** [comment]
这部电影可以分享下么，我修改了测下
