### ISSUE TITLE
qb 修复自动标签的各位先别更  更了有问题  

### ISSUE THREAD

**Issue by iovejieba** [hsuyelin/nas-tools#16]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
直接替换或修改曾行会报错！

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
@iovejieba 我版本都没更新，有啥问题，展开说说

**Comment by iovejieba** [comment]
> @iovejieba 我版本都没更新，有啥问题，展开说说

额  那我去换下 刚才没导出日志  我就换回来了

**Comment by iovejieba** [comment]
2023-07-29 07:34:15	stdout	ModuleNotFoundError: No module named 'app.downloader.client.qbittorrent'
2023-07-29 07:34:15	stdout	    from .qbittorrent import Qbittorrent
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/downloader/client/__init__.py", line 1, in <module>
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-07-29 07:34:15	stdout	  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-07-29 07:34:15	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2023-07-29 07:34:15	stdout	  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-07-29 07:34:15	stdout	    packages = importlib.import_module(package).__path__
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/helper/submodule_helper.py", line 17, in import_submodules
2023-07-29 07:34:15	stdout	    self._downloader_schema = SubmoduleHelper.import_submodules(
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/downloader/downloader.py", line 53, in __init__
2023-07-29 07:34:15	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:34:15	stdout	    self.downloader = Downloader()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/searcher.py", line 30, in init_config
2023-07-29 07:34:15	stdout	    self.init_config()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/searcher.py", line 27, in __init__
2023-07-29 07:34:15	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:34:15	stdout	    self.searcher = Searcher()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/subscribe.py", line 44, in init_config
2023-07-29 07:34:15	stdout	    self.init_config()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/subscribe.py", line 39, in __init__
2023-07-29 07:34:15	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:34:15	stdout	    self.SCHEDULER.add_job(Subscribe().subscribe_search_all, 'interval', hours=search_rss_interval)
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/scheduler.py", line 90, in run_service
2023-07-29 07:34:15	stdout	    self.run_service()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/scheduler.py", line 36, in init_config
2023-07-29 07:34:15	stdout	    self.init_config()
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/scheduler.py", line 30, in __init__
2023-07-29 07:34:15	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:34:15	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:34:15	stdout	    Scheduler()
2023-07-29 07:34:15	stdout	  File "/nas-tools/web/action.py", line 335, in start_service
2023-07-29 07:34:15	stdout	    WebAction.start_service()
2023-07-29 07:34:15	stdout	  File "/nas-tools/run.py", line 106, in start_service
2023-07-29 07:34:15	stdout	    start_service()
2023-07-29 07:34:15	stdout	  File "/nas-tools/run.py", line 115, in <module>
2023-07-29 07:34:15	stdout	Traceback (most recent call last):


2023-07-29 07:33:58	stdout	TabError: inconsistent use of tabs and spaces in indentation
2023-07-29 07:33:58	stdout	    return self.qbc.torrents_delete_tags(torrent_hashes=ids, tags=tag)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/downloader/client/qbittorrent.py", line 237
2023-07-29 07:33:58	stdout	    from .qbittorrent import Qbittorrent
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/downloader/client/__init__.py", line 1, in <module>
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-07-29 07:33:58	stdout	  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-07-29 07:33:58	stdout	    return _bootstrap._gcd_import(name[level:], package, level)
2023-07-29 07:33:58	stdout	  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-07-29 07:33:58	stdout	    packages = importlib.import_module(package).__path__
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/helper/submodule_helper.py", line 17, in import_submodules
2023-07-29 07:33:58	stdout	    self._downloader_schema = SubmoduleHelper.import_submodules(
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/downloader/downloader.py", line 53, in __init__
2023-07-29 07:33:58	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:33:58	stdout	    self.downloader = Downloader()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/searcher.py", line 30, in init_config
2023-07-29 07:33:58	stdout	    self.init_config()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/searcher.py", line 27, in __init__
2023-07-29 07:33:58	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:33:58	stdout	    self.searcher = Searcher()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/subscribe.py", line 44, in init_config
2023-07-29 07:33:58	stdout	    self.init_config()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/subscribe.py", line 39, in __init__
2023-07-29 07:33:58	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:33:58	stdout	    self.SCHEDULER.add_job(Subscribe().subscribe_search_all, 'interval', hours=search_rss_interval)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/scheduler.py", line 90, in run_service
2023-07-29 07:33:58	stdout	    self.run_service()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/scheduler.py", line 36, in init_config
2023-07-29 07:33:58	stdout	    self.init_config()
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/scheduler.py", line 30, in __init__
2023-07-29 07:33:58	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023-07-29 07:33:58	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023-07-29 07:33:58	stdout	    Scheduler()
2023-07-29 07:33:58	stdout	  File "/nas-tools/web/action.py", line 335, in start_service
2023-07-29 07:33:58	stdout	    WebAction.start_service()
2023-07-29 07:33:58	stdout	  File "/nas-tools/run.py", line 106, in start_service
2023-07-29 07:33:58	stdout	    start_service()
2023-07-29 07:33:58	stdout	  File "/nas-tools/run.py", line 115, in <module>
2023-07-29 07:33:58	stdout	Traceback (most recent call last):

**Comment by iovejieba** [comment]
看着....额   大小写？

**Comment by hsuyelin** [comment]
> 看着....额 大小写？

抽空本地调试看看

**Comment by iovejieba** [comment]
> > 看着....额 大小写？
> 
> 抽空本地调试看看

ok

**Comment by hsuyelin** [comment]
> > > 看着....额 大小写？
> > 
> > 
> > 抽空本地调试看看
> 
> ok
我试了没问题，等我新版本你更新下，有问题在反馈我先关了
