### ISSUE TITLE
站点签到时候，后台出现浮点数错误

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#19]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.9 65e3d92
>
> 环境: docker
>

## 你遇到什么问题了？

> 站点签到时候，后台出现了浮点数错误，估计是没有正确匹配文本导致的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 目前没有人提出，不影响使用，但是经常会出现，一个小问题应该比较好修复

## 你期望的结果

> 不影响使用，但是希望大佬可以修复一下这个小问题

## 给出程序界面截图、后台运行日志或配置文件

> docker日志：
2023-08-02 00:31:25,002 INFO: Challenge not detected!
2023-08-02 00:31:26,689 INFO: Challenge not detected!
2023-08-02 00:31:26,772 INFO: Challenge not detected!
2023-08-02 00:31:26,844 INFO: Challenge not detected!
2023-08-02 00:31:27,545 INFO: Challenge not detected!

Exception: could not convert string to float: '.'
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/utils/string_utils.py", line 153, in str_float
    float_val = float(text.strip().replace(',', ''))
ValueError: could not convert string to float: '.'

2023-08-02 00:31:30,436 INFO: Challenge not detected!
2023-08-02 00:31:40,210 INFO: Challenge not detected!
2023-08-02 00:31:42,063 INFO: Challenge not detected!
2023-08-02 00:31:43,006 INFO: Challenge not detected!
2023-08-02 00:31:43,035 INFO: Challenge not detected!
2023-08-02 00:31:45,189 INFO: Challenge not detected!
2023-08-02 00:31:47,199 INFO: Challenge not detected!

**Comment by hsuyelin** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.2.9 [65e3d92](https://github.com/hsuyelin/nas-tools/commit/65e3d929aa67e87dd13b393782362cba8cd4ab89)
> > 环境: docker
> 
> ## 你遇到什么问题了？
> > 站点签到时候，后台出现了浮点数错误，估计是没有正确匹配文本导致的
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > 目前没有人提出，不影响使用，但是经常会出现，一个小问题应该比较好修复
> 
> ## 你期望的结果
> > 不影响使用，但是希望大佬可以修复一下这个小问题
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> > docker日志：
> > 2023-08-02 00:31:25,002 INFO: Challenge not detected!
> > 2023-08-02 00:31:26,689 INFO: Challenge not detected!
> > 2023-08-02 00:31:26,772 INFO: Challenge not detected!
> > 2023-08-02 00:31:26,844 INFO: Challenge not detected!
> > 2023-08-02 00:31:27,545 INFO: Challenge not detected!
> 
> Exception: could not convert string to float: '.' Callstack: Traceback (most recent call last): File "/nas-tools/app/utils/string_utils.py", line 153, in str_float float_val = float(text.strip().replace(',', '')) ValueError: could not convert string to float: '.'
> 
> 2023-08-02 00:31:30,436 INFO: Challenge not detected! 2023-08-02 00:31:40,210 INFO: Challenge not detected! 2023-08-02 00:31:42,063 INFO: Challenge not detected! 2023-08-02 00:31:43,006 INFO: Challenge not detected! 2023-08-02 00:31:43,035 INFO: Challenge not detected! 2023-08-02 00:31:45,189 INFO: Challenge not detected! 2023-08-02 00:31:47,199 INFO: Challenge not detected!

已解决：https://github.com/hsuyelin/nas-tools/commit/0caa4a7e0cd049fd4ca311bda032e6b40fb86ed7
