### ISSUE TITLE
启动inotify报错,inotify watch limit reached,NAS沒權限執行命令

### ISSUE THREAD

**Issue by strawberry1018** [hsuyelin/nas-tools#267]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

hsuyelin/nas-tools:latest

### 问题类型

主程序运行问题

### 问题描述

NAS不開放ROOT權限,有沒有其他辦法解決這個問題,已經兩天了搞不好,現在無法啟動

### 发生问题时系统日志和配置文件

```bash
2023/9/13 10:07:33  RuntimeError: cannot schedule new futures after shutdown
2023/9/13 10:07:33      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/13 10:07:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/13 10:07:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:07:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:07:33      self._do_submit_job(job, run_times)
2023/9/13 10:07:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:07:33      executor.submit_job(job, run_times)
2023/9/13 10:07:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:07:33  Traceback (most recent call last):
2023/9/13 10:07:33  Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-09-13 10:07:33 CST)" to executor "default"
2023/9/13 10:06:33  RuntimeError: cannot schedule new futures after interpreter shutdown
2023/9/13 10:06:33      raise RuntimeError('cannot schedule new futures after '
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
2023/9/13 10:06:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:33      self._do_submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:33      executor.submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:33  Traceback (most recent call last):
2023/9/13 10:06:33  Error submitting job "SpeedLimiter.__check_playing_sessions (trigger: interval[0:05:00], next run at: 2023-09-13 10:06:33 CST)" to executor "default"
2023/9/13 10:06:33  RuntimeError: cannot schedule new futures after interpreter shutdown
2023/9/13 10:06:33      raise RuntimeError('cannot schedule new futures after '
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
2023/9/13 10:06:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:33      self._do_submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:33      executor.submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:33  Traceback (most recent call last):
2023/9/13 10:06:33  Error submitting job "BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], next run at: 2023-09-13 10:06:33 CST)" to executor "default"
2023/9/13 10:06:33  RuntimeError: cannot schedule new futures after interpreter shutdown
2023/9/13 10:06:33      raise RuntimeError('cannot schedule new futures after '
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
2023/9/13 10:06:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:33      self._do_submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:33      executor.submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:33  Traceback (most recent call last):
2023/9/13 10:06:33  Error submitting job "BrushTask.check_task_rss (trigger: interval[0:10:00], next run at: 2023-09-13 10:06:33 CST)" to executor "default"
2023/9/13 10:06:33  RuntimeError: cannot schedule new futures after shutdown
2023/9/13 10:06:33      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/13 10:06:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:33      self._do_submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:33      executor.submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:33  Traceback (most recent call last):
2023/9/13 10:06:33  Error submitting job "Subscribe.subscribe_search (trigger: interval[0:05:00], next run at: 2023-09-13 10:06:33 CST)" to executor "default"
2023/9/13 10:06:33  RuntimeError: cannot schedule new futures after shutdown
2023/9/13 10:06:33      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/13 10:06:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:33      self._do_submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:33      executor.submit_job(job, run_times)
2023/9/13 10:06:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:33  Traceback (most recent call last):
2023/9/13 10:06:33  Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-09-13 10:06:33 CST)" to executor "default"
2023/9/13 10:06:17  RuntimeError: cannot schedule new futures after shutdown
2023/9/13 10:06:17      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/13 10:06:17    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/13 10:06:17      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:06:17    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:06:17      self._do_submit_job(job, run_times)
2023/9/13 10:06:17    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:06:17      executor.submit_job(job, run_times)
2023/9/13 10:06:17    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:06:17  Traceback (most recent call last):
2023/9/13 10:06:17  Error submitting job "MetaHelper.save_meta_data (trigger: interval[0:10:00], next run at: 2023-09-13 10:06:17 CST)" to executor "default"
2023/9/13 10:05:33  RuntimeError: cannot schedule new futures after interpreter shutdown
2023/9/13 10:05:33      raise RuntimeError('cannot schedule new futures after '
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
2023/9/13 10:05:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:05:33      self._do_submit_job(job, run_times)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:05:33      executor.submit_job(job, run_times)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:05:33  Traceback (most recent call last):
2023/9/13 10:05:33  Error submitting job "TorrentTransfer.check_recheck (trigger: interval[0:03:00], next run at: 2023-09-13 10:05:33 CST)" to executor "default"
2023/9/13 10:05:33  RuntimeError: cannot schedule new futures after shutdown
2023/9/13 10:05:33      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/13 10:05:33      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/13 10:05:33      self._do_submit_job(job, run_times)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/13 10:05:33      executor.submit_job(job, run_times)
2023/9/13 10:05:33    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/13 10:05:33  Traceback (most recent call last):
2023/9/13 10:05:33  Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-09-13 10:05:33 CST)" to executor "default"
2023/9/13 10:04:33  RuntimeError: cannot schedule new futures after shutdown
```

**Comment by zjjxwhh** [comment]
https://github.com/hsuyelin/nas-tools/issues/255#issuecomment-1713964603 这个报错，你是 Windows 系统的 NAS？

**Comment by strawberry1018** [comment]
> [#255 (comment)](https://github.com/hsuyelin/nas-tools/issues/255#issuecomment-1713964603) 这个报错，你是 Windows 系统的 NAS？

[極空間 Z4 ](https://www.zspace.cn/z4/)

**Comment by zjjxwhh** [comment]
> > [#255 (comment)](https://github.com/hsuyelin/nas-tools/issues/255#issuecomment-1713964603) 这个报错，你是 Windows 系统的 NAS？
> 
> [極空間 Z4 ](https://www.zspace.cn/z4/)

应该是 cmd 下用 SSH 连接到 NAS 之后执行 `sudo` 那一串命令
你这个报错怎么看着像是 cmd 直接执行的报错（因为 windows 下确实没有 `sudo` 命令

如果你确认你操作的没问题的话，那只能等大佬再看看了

**Comment by strawberry1018** [comment]
> > > [#255 (comment)](https://github.com/hsuyelin/nas-tools/issues/255#issuecomment-1713964603) 这个报错，你是 Windows 系统的 NAS？
> > 
> > 
> > [極空間 Z4 ](https://www.zspace.cn/z4/)
> 
> 应该是 cmd 下用 SSH 连接到 NAS 之后执行 `sudo` 那一串命令 你这个报错怎么看着像是 cmd 直接执行的报错（因为 windows 下确实没有 `sudo` 命令
> 
> 如果你确认你操作的没问题的话，那只能等大佬再看看了

因為官方沒有開房root權限,

**Comment by hsuyelin** [comment]
看看readme @strawberry1018 , 没有权限自己查阅下如何开启nas的root权限

**Comment by strawberry1018** [comment]
> 看看readme @strawberry1018 , 没有权限自己查阅下如何开启nas的root权限

大哥,有没有其他解决方案,极空间不给开放root权限
