### ISSUE TITLE
[错误报告]: 看起来好像是在文件转移的时候进行了订阅搜索？数据库被多个线程尝试写入导致整个容器卡死

### ISSUE THREAD

**Issue by HankunYu** [hsuyelin/nas-tools#313]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9 d95848c

### 问题类型

主程序运行问题

### 问题描述

因为想重新刮削元数据，所以把很多老资源重新转移了一遍。已经不是第一次发生这个情况，经常转移到一半的时候整个容器卡死，甚至无法正常退出只能重启整个docker。

日志如下。

### 发生问题时系统日志和配置文件

```bash
Traceback (most recent call last):
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-09-21 10:00:55     self.dialect.do_execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-09-21 10:00:55     cursor.execute(statement, parameters)
2023-09-21 10:00:55 sqlite3.OperationalError: database is locked
2023-09-21 10:00:55 
2023-09-21 10:00:55 The above exception was the direct cause of the following exception:
2023-09-21 10:00:55 
2023-09-21 10:00:55 Traceback (most recent call last):
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
2023-09-21 10:00:55     retval = job.func(*job.args, **job.kwargs)
2023-09-21 10:00:55   File "/nas-tools/app/subscribe.py", line 690, in subscribe_search
2023-09-21 10:00:55     self.subscribe_search_movie(state=state)
2023-09-21 10:00:55   File "/nas-tools/app/subscribe.py", line 705, in subscribe_search_movie
2023-09-21 10:00:55     rss_movies = self.get_subscribe_movies(state=state)
2023-09-21 10:00:55   File "/nas-tools/app/subscribe.py", line 405, in get_subscribe_movies
2023-09-21 10:00:55     rss_movies = self.dbhelper.get_rss_movies(rssid=rid, state=state)
2023-09-21 10:00:55   File "/nas-tools/app/helper/db_helper.py", line 576, in get_rss_movies
2023-09-21 10:00:55     return self._db.query(RSSMOVIES).filter(RSSMOVIES.STATE == state).all()
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2692, in all
2023-09-21 10:00:55     return self._iter().all()  # type: ignore
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
2023-09-21 10:00:55     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
2023-09-21 10:00:55     return self._execute_internal(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
2023-09-21 10:00:55     result: Result[Any] = compile_state_cls.orm_execute_statement(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
2023-09-21 10:00:55     result = conn.execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
2023-09-21 10:00:55     return meth(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
2023-09-21 10:00:55     return connection._execute_clauseelement(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
2023-09-21 10:00:55     ret = self._execute_context(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
2023-09-21 10:00:55     return self._exec_single_context(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
2023-09-21 10:00:55     self._handle_dbapi_exception(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
2023-09-21 10:00:55     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-09-21 10:00:55     self.dialect.do_execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-09-21 10:00:55     cursor.execute(statement, parameters)
2023-09-21 10:00:55 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
2023-09-21 10:00:55 [SQL: SELECT "RSS_MOVIES"."ID" AS "RSS_MOVIES_ID", "RSS_MOVIES"."NAME" AS "RSS_MOVIES_NAME", "RSS_MOVIES"."YEAR" AS "RSS_MOVIES_YEAR", "RSS_MOVIES"."KEYWORD" AS "RSS_MOVIES_KEYWORD", "RSS_MOVIES"."TMDBID" AS "RSS_MOVIES_TMDBID", "RSS_MOVIES"."IMAGE" AS "RSS_MOVIES_IMAGE", "RSS_MOVIES"."RSS_SITES" AS "RSS_MOVIES_RSS_SITES", "RSS_MOVIES"."SEARCH_SITES" AS "RSS_MOVIES_SEARCH_SITES", "RSS_MOVIES"."OVER_EDITION" AS "RSS_MOVIES_OVER_EDITION", "RSS_MOVIES"."FILTER_ORDER" AS "RSS_MOVIES_FILTER_ORDER", "RSS_MOVIES"."FILTER_RESTYPE" AS "RSS_MOVIES_FILTER_RESTYPE", "RSS_MOVIES"."FILTER_PIX" AS "RSS_MOVIES_FILTER_PIX", "RSS_MOVIES"."FILTER_RULE" AS "RSS_MOVIES_FILTER_RULE", "RSS_MOVIES"."FILTER_TEAM" AS "RSS_MOVIES_FILTER_TEAM", "RSS_MOVIES"."FILTER_INCLUDE" AS "RSS_MOVIES_FILTER_INCLUDE", "RSS_MOVIES"."FILTER_EXCLUDE" AS "RSS_MOVIES_FILTER_EXCLUDE", "RSS_MOVIES"."SAVE_PATH" AS "RSS_MOVIES_SAVE_PATH", "RSS_MOVIES"."DOWNLOAD_SETTING" AS "RSS_MOVIES_DOWNLOAD_SETTING", "RSS_MOVIES"."FUZZY_MATCH" AS "RSS_MOVIES_FUZZY_MATCH", "RSS_MOVIES"."STATE" AS "RSS_MOVIES_STATE", "RSS_MOVIES"."DESC" AS "RSS_MOVIES_DESC", "RSS_MOVIES"."NOTE" AS "RSS_MOVIES_NOTE" 
2023-09-21 10:00:55 FROM "RSS_MOVIES" 
2023-09-21 10:00:55 WHERE "RSS_MOVIES"."STATE" = ?]
2023-09-21 10:00:55 [parameters: ('D',)]
2023-09-21 10:00:55 (Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-09-21 10:00:55 Job "BrushTask.check_task_rss (trigger: interval[0:10:00], next run at: 2023-09-21 17:10:50 CST)" raised an exception
2023-09-21 10:00:55 Traceback (most recent call last):
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-09-21 10:00:55     self.dialect.do_execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-09-21 10:00:55     cursor.execute(statement, parameters)
2023-09-21 10:00:55 sqlite3.OperationalError: database is locked
2023-09-21 10:00:55 
2023-09-21 10:00:55 The above exception was the direct cause of the following exception:
2023-09-21 10:00:55 
2023-09-21 10:00:55 Traceback (most recent call last):
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
2023-09-21 10:00:55     retval = job.func(*job.args, **job.kwargs)
2023-09-21 10:00:55   File "/nas-tools/app/brushtask.py", line 159, in check_task_rss
2023-09-21 10:00:55     taskinfo = self.get_brushtask_info(taskid)
2023-09-21 10:00:55   File "/nas-tools/app/brushtask.py", line 145, in get_brushtask_info
2023-09-21 10:00:55     self.load_brushtasks()
2023-09-21 10:00:55   File "/nas-tools/app/brushtask.py", line 97, in load_brushtasks
2023-09-21 10:00:55     brushtasks = self.dbhelper.get_brushtasks()
2023-09-21 10:00:55   File "/nas-tools/app/helper/db_helper.py", line 1698, in get_brushtasks
2023-09-21 10:00:55     .order_by(cast(CONFIGSITE.PRI, Integer).asc()).all()
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2692, in all
2023-09-21 10:00:55     return self._iter().all()  # type: ignore
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
2023-09-21 10:00:55     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
2023-09-21 10:00:55     return self._execute_internal(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
2023-09-21 10:00:55     result: Result[Any] = compile_state_cls.orm_execute_statement(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
2023-09-21 10:00:55     result = conn.execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
2023-09-21 10:00:55     return meth(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
2023-09-21 10:00:55     return connection._execute_clauseelement(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
2023-09-21 10:00:55     ret = self._execute_context(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
2023-09-21 10:00:55     return self._exec_single_context(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
2023-09-21 10:00:55     self._handle_dbapi_exception(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
2023-09-21 10:00:55     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
2023-09-21 10:00:55     self.dialect.do_execute(
2023-09-21 10:00:55   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
2023-09-21 10:00:55     cursor.execute(statement, parameters)
2023-09-21 10:00:55 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
2023-09-21 10:00:55 [SQL: SELECT "SITE_BRUSH_TASK"."ID" AS "SITE_BRUSH_TASK_ID", "SITE_BRUSH_TASK"."NAME" AS "SITE_BRUSH_TASK_NAME", "SITE_BRUSH_TASK"."SITE" AS "SITE_BRUSH_TASK_SITE", "SITE_BRUSH_TASK"."RSSURL" AS "SITE_BRUSH_TASK_RSSURL", "SITE_BRUSH_TASK"."FREELEECH" AS "SITE_BRUSH_TASK_FREELEECH", "SITE_BRUSH_TASK"."RSS_RULE" AS "SITE_BRUSH_TASK_RSS_RULE", "SITE_BRUSH_TASK"."REMOVE_RULE" AS "SITE_BRUSH_TASK_REMOVE_RULE", "SITE_BRUSH_TASK"."SEED_SIZE" AS "SITE_BRUSH_TASK_SEED_SIZE", "SITE_BRUSH_TASK"."INTEVAL" AS "SITE_BRUSH_TASK_INTEVAL", "SITE_BRUSH_TASK"."LABEL" AS "SITE_BRUSH_TASK_LABEL", "SITE_BRUSH_TASK"."UP_LIMIT" AS "SITE_BRUSH_TASK_UP_LIMIT", "SITE_BRUSH_TASK"."DL_LIMIT" AS "SITE_BRUSH_TASK_DL_LIMIT", "SITE_BRUSH_TASK"."SAVEPATH" AS "SITE_BRUSH_TASK_SAVEPATH", "SITE_BRUSH_TASK"."DOWNLOADER" AS "SITE_BRUSH_TASK_DOWNLOADER", "SITE_BRUSH_TASK"."TRANSFER" AS "SITE_BRUSH_TASK_TRANSFER", "SITE_BRUSH_TASK"."DOWNLOAD_COUNT" AS "SITE_BRUSH_TASK_DOWNLOAD_COUNT", "SITE_BRUSH_TASK"."REMOVE_COUNT" AS "SITE_BRUSH_TASK_REMOVE_COUNT", "SITE_BRUSH_TASK"."DOWNLOAD_SIZE" AS "SITE_BRUSH_TASK_DOWNLOAD_SIZE", "SITE_BRUSH_TASK"."UPLOAD_SIZE" AS "SITE_BRUSH_TASK_UPLOAD_SIZE", "SITE_BRUSH_TASK"."SENDMESSAGE" AS "SITE_BRUSH_TASK_SENDMESSAGE", "SITE_BRUSH_TASK"."STATE" AS "SITE_BRUSH_TASK_STATE", "SITE_BRUSH_TASK"."LST_MOD_DATE" AS "SITE_BRUSH_TASK_LST_MOD_DATE" 
2023-09-21 10:00:55 FROM "SITE_BRUSH_TASK" JOIN "CONFIG_SITE" ON "SITE_BRUSH_TASK"."SITE" = "CONFIG_SITE"."ID" ORDER BY CAST("CONFIG_SITE"."PRI" AS INTEGER) ASC]
2023-09-21 10:00:55 (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by hsuyelin** [comment]
看着日志很像啊，临时方案如果大量入库时，建议先手动暂停rss、刷流，后面我会判断当前状态来处理
