### ISSUE TITLE
 开始初始化数据库...报错，然后运行中也会有| ERROR    | logging:exception:line:1512 | expected string or bytes-like object

### ISSUE THREAD

**Issue by chuan1127** [hsuyelin/nas-tools#320]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

主程序运行问题

### 问题描述

当程序 运行之后就提示
开始初始化数据库...
(sqlite3.OperationalError) no such table: alembic_version
[SQL: delete from alembic_version where 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)，这里报错，然后程序运行中的时候，会时不时的输出以下日志. 目前还不知道啥 原因.

### 发生问题时系统日志和配置文件

```bash
[INFO] 主程序更新成功
[INFO] 以PUID=0，PGID=0的身份启动程序...
usermod: no changes
正在加载配置：/config/config.yaml
正在加载flask环境变量: /nas-tools/.flaskenv
NAStool 当前版本号：v3.3.9
开始初始化数据库...
(sqlite3.OperationalError) no such table: alembic_version
[SQL: delete from alembic_version where 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
开始启动服务...
Pending jobs:
    SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-09-22 12:29:40 CST)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-09-22 12:28:41 CST)
Pending jobs:
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
Expecting value: line 1 column 1 (char 0)
Pending jobs:
    RssChecker.check_task_rss (trigger: interval[0:30:00], pending)
    RssChecker.check_task_rss (trigger: interval[0:30:00], pending)
expected string or bytes-like object
Wrong number of fields; got 4, expected 5
Wrong number of fields; got 4, expected 5
Pending jobs:
    DoubanSync.sync (trigger: interval[8:00:00], pending)
Wrong number of fields; got 4, expected 5
Unrecognized expression "?" for field "month"
 * Serving Flask app 'web.main'
 * Debug mode: on



TypeError: expected string or bytes-like object
Execution of job "Subscribe.subscribe_search (trigger: interval[0:05:00], next run at: 2023-09-22 12:26:14 CST)" skipped: maximum number of running instances reached (1)
2023-09-22 12:26:19,043 WARNING: 【Indexer】ACG.RIP 未搜索到数据
2023-09-22 12:26:19,044 INFO: 【Indexer】所有站点搜索完成，有效资源数：0，总耗时 31 秒
2023-09-22 12:26:19,044 INFO: 【Searcher】龙与地下城：侠盗荣耀 未搜索到资源,尝试通过 Dungeons & Dragons: Honor Among Thieves 重新搜索 ...
2023-09-22 12:26:19,045 INFO: 处理事件：search.start - [<function Webhook.send at 0x15052a884dc0>]
2023-09-22 12:26:19,057 INFO: 【Indexer】开始并行搜索 Dungeons & Dragons: Honor Among Thieves，线程数：10 ...




2023-09-22 12:26:19,058 WARNING: 【Sites】站点 https://hdmayi.com/index.php 触发流控规则，访问间隔不得小于 900 秒，上次访问时间：2023-09-22 12:17:14
2023-09-22 12:26:19,059 WARNING: 【Sites】站点 https://piggo.me/index.php 触发流控规则，访问间隔不得小于 900 秒，上次访问时间：2023-09-22 12:17:14
2023-09-22 12:26:19,059 WARNING: 【Sites】站点 https://kp.m-team.cc/index.php 触发流控规则，访问间隔不得小于 900 秒，上次访问时间：2023-09-22 12:17:14
2023-09-22 12:26:19,060 INFO: 【Indexer】开始搜索Indexer：动漫花园 ...
2023-09-22 12:26:19,060 INFO: 【Indexer】开始搜索Indexer：蜜柑 ...
2023-09-22 12:26:19,061 INFO: 【Indexer】开始搜索Indexer：NYAA ...
2023-09-22 12:26:19,061 INFO: 【Indexer】开始搜索Indexer：漫喵 ...
2023-09-22 12:26:19,062 INFO: 【Indexer】开始搜索Indexer：ACG.RIP ...
2023-09-22 12:26:19,062 INFO: 【Indexer】开始搜索Indexer：EZTV ...
2023-09-22 12:26:19,064 INFO: 【Indexer】开始搜索Indexer：NYAA(INK) ...
2023-09-22 12:26:19,074 INFO: 【Spider】开始请求：https://mikanime.tv/Home/Search?searchstr=Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:19,075 INFO: 【Spider】开始请求：https://dmhy.org/topics/list?keyword=Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:19,077 INFO: 【Spider】开始请求：https://www.comicat.org/search.php?keyword=Dungeons%20Dragons%20Honor%20Among%20Thieves&page=0
2023-09-22 12:26:19,078 INFO: 【Spider】开始请求：https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:19,079 INFO: 【Spider】开始请求：https://nyaa.si/?f=0&c=0_0&q=Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:19,081 INFO: 【Spider】开始请求：https://eztv.re/search/Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:19,084 INFO: 【Spider】开始请求：https://nyaa.ink/?f=0&c=0_0&q=Dungeons%20Dragons%20Honor%20Among%20Thieves
2023-09-22 12:26:20,093 WARNING: 【Indexer】漫喵 返回数据：1
2023-09-22 12:26:20,093 INFO: 【Indexer】漫喵 1 条数据中，过滤 0，不匹配 0，错误 1，有效 0，耗时 1 秒
2023-09-22 12:26:20,108 WARNING: 【Indexer】NYAA 未搜索到数据
2023-09-22 12:26:20,126 WARNING: 【Indexer】EZTV 未搜索到数据
2023-09-22 12:26:21,086 WARNING: 【Indexer】动漫花园 未搜索到数据
2023-09-22 12:26:21,098 WARNING: 【Indexer】NYAA(INK) 未搜索到数据
2023-09-22 12:26:21,116 WARNING: 【Indexer】蜜柑 未搜索到数据
2023-09-22 12:26:24.113 | ERROR    | logging:exception:line:1512 | expected string or bytes-like object
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x1505272d03a0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x150532fe2050>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x150529d86020>
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x150532ff2680>
    └ <urllib3.connection.HTTPSConnection object at 0x1505272d03a0>
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        └ <function _ssl_wrap_socket_and_match_hostname at 0x15053305fb50>
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               └ <function ssl_wrap_socket at 0x15053305c3a0>
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               │                     │     │        │           └ 'acg.rip'
               │                     │     │        └ False
               │                     │     └ <ssl.SSLContext object at 0x1505261c07c0>
               │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
               └ <function _ssl_wrap_socket_impl at 0x15053305c550>
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'acg.rip'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x150533bc9240>
           └ <ssl.SSLContext object at 0x1505261c07c0>
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod(<function SSLSocket._create at 0x150533bcadd0>)>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x1505261c07c0>
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x1505346300d0>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               │    └ <function HTTPConnectionPool._make_request at 0x150532fe1c60>
               └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x150529d86020>
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
          └ SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))

urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x150532fe1e10>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x150529d86020>
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x150532ffdb40>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
          │             │      │    │            └ SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))
          │             │      │    └ SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))
          │             │      └ '/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x150529d86020>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acg.rip', port=443): Max retries exceeded with url: /?term=Dungeons%20Dragons%20Honor%20Among%20Thieves (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 552, in deal_request
    else request.get_response_from_cached(save_cached=False)
         │       └ <function Request.get_response_from_cached at 0x15052b299360>
         └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 517, in get_response_from_cached
    response_obj = self.get_response(save_cached=save_cached)
                   │    │                        └ False
                   │    └ <function Request.get_response at 0x15052b298ca0>
                   └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 396, in get_response
    response = self._session_downloader.download(self)
               │    │                            └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>
               │    └ <property object at 0x15052b3b7880>
               └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>

  File "/nas-tools/third_party/feapder/feapder/network/downloader/_requests.py", line 42, in download
    response = self._session.request(
               │    └ <property object at 0x15052b3b7c90>
               └ <feapder.network.downloader._requests.RequestsSessionDownloader object at 0x150529e04670>

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 22, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x150532f4f760>
           └ <requests.sessions.Session object at 0x150529e04be0>
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 22, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x150532f4ec20>
        └ <requests.adapters.HTTPAdapter object at 0x150529d84760>
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='acg.rip', port=443): Max retries exceeded with url: /?term=Dungeons%20Dragons%20Honor%20Among%20Thieves (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x150535244040>
    └ <AirSpiderParserControl(Thread-423, started daemon 23111810026288)>
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function AirSpiderParserControl.run at 0x15052b299a20>
    └ <AirSpiderParserControl(Thread-423, started daemon 23111810026288)>

> File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 487, in run
    self.deal_request(request)
    │    │            └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>
    │    └ <function AirSpiderParserControl.deal_request at 0x15052b299ab0>
    └ <AirSpiderParserControl(Thread-423, started daemon 23111810026288)>

  File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 617, in deal_request
    request.del_proxy()
    │       └ <function Request.del_proxy at 0x15052b298ee0>
    └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 431, in del_proxy
    proxy = self.get_proxy()
            │    └ <function Request.get_proxy at 0x15052b298e50>
            └ <Request https://acg.rip/?term=Dungeons%20Dragons%20Honor%20Among%20Thieves>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 426, in get_proxy
    return re.sub(
           │  └ <function sub at 0x15053520f7f0>
           └ <module 're' from '/usr/local/lib/python3.10/re.py'>

  File "/usr/local/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           │        │        │          │     │       └ 0
           │        │        │          │     └ None
           │        │        │          └ ''
           │        │        └ 0
           │        └ 'http.*?//'
           └ <function _compile at 0x15053520fd00>

TypeError: expected string or bytes-like object
2023-09-22 12:26:50,127 WARNING: 【Indexer】ACG.RIP 未搜索到数据
2023-09-22 12:26:50,128 INFO: 【Indexer】所有站点搜索完成，有效资源数：0，总耗时 31 秒
2023-09-22 12:26:50,128 INFO: 【Searcher】Dungeons & Dragons: Honor Among Thieves 未搜索到任何资源
2023-09-22 12:26:50,176 INFO: 【Meta】正在查询TMDB电影：447277 ...
2023-09-22 12:26:51,816 INFO: 【Meta】447277 查询结果：小美人鱼
2023-09-22 12:26:52,023 INFO: 【Downloader】媒体库中已存在电影：
```

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/7304f503-7d4c-4e2c-ada1-dc68d84d0980)

**Comment by chuan1127** [comment]
你好，按照你的方法，我删掉了，但是重启之后，表格会重新生成. 所以不知道怎么办了
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年9月22日 15:14
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [hsuyelin/nas-tools]  开始初始化数据库...报错，然后运行中也会有| ERROR    | logging:exception:line:1512 | expected string or bytes-like object (Issue #320)
