### ISSUE TITLE
[错误报告]:  ~~看起来webhook插件有时候会导致问题~~ 订正:错误基本都是由内建BT索引错误引起的

### ISSUE THREAD

**Issue by HankunYu** [hsuyelin/nas-tools#331]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.9 3e9d42c

### 问题类型

主程序运行问题

### 问题描述

偶然会遇到的问题,不是每次触发webhook都会有问题.感觉挺难定位问题出在哪里....
我webhook发送到本地一个python跑的flask

结果导致整个nastool卡死

### 发生问题时系统日志和配置文件

```bash
2023-09-23 22:42:52 Object of type MediaType is not JSON serializable Traceback (most recent call last):
2023-09-23 22:42:52   File "/nas-tools/app/plugins/plugin_manager.py", line 133, in run_plugin
2023-09-23 22:42:52     return getattr(self._running_plugins[pid], method)(*args, **kwargs)
2023-09-23 22:42:52   File "/nas-tools/app/plugins/modules/webhook.py", line 99, in send
2023-09-23 22:42:52     ret = RequestUtils(content_type="application/json").post_res(self._webhook_url, json=event_info)
2023-09-23 22:42:52   File "/nas-tools/app/utils/http_utils.py", line 141, in post_res
2023-09-23 22:42:52     return requests.post(url,
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
2023-09-23 22:42:52     return request("post", url, data=data, json=json, **kwargs)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2023-09-23 22:42:52     return session.request(method=method, url=url, **kwargs)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
2023-09-23 22:42:52     prep = self.prepare_request(req)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
2023-09-23 22:42:52     p.prepare(
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
2023-09-23 22:42:52     self.prepare_body(data, files, json)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
2023-09-23 22:42:52     body = complexjson.dumps(json, allow_nan=False)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
2023-09-23 22:42:52     **kw).encode(obj)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
2023-09-23 22:42:52     chunks = self.iterencode(o, _one_shot=True)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
2023-09-23 22:42:52     return _iterencode(o, 0)
2023-09-23 22:42:52   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
2023-09-23 22:42:52     raise TypeError(f'Object of type {o.__class__.__name__} '
2023-09-23 22:42:52 TypeError: Object of type MediaType is not JSON serializable
2023-09-23 22:42:52 
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
2023-09-23 22:42:52 argument of type 'NoneType' is not iterable
```

**Comment by HankunYu** [comment]
不确定有没有关系,还遇到这个问题 关于openssl, 这个发生在搜索资源的时候
2023-09-23 23:19:15 Traceback (most recent call last):
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
2023-09-23 23:19:15     self._validate_conn(conn)
2023-09-23 23:19:15     │    │              └ <urllib3.connection.HTTPSConnection object at 0x7f17ee6974c0>
2023-09-23 23:19:15     │    └ <function HTTPSConnectionPool._validate_conn at 0x7f17f91bf0a0>
2023-09-23 23:19:15     └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f17ee695de0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
2023-09-23 23:19:15     conn.connect()
2023-09-23 23:19:15     │    └ <function HTTPSConnection.connect at 0x7f17f91af6d0>
2023-09-23 23:19:15     └ <urllib3.connection.HTTPSConnection object at 0x7f17ee6974c0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
2023-09-23 23:19:15     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
2023-09-23 23:19:15                         └ <function _ssl_wrap_socket_and_match_hostname at 0x7f17f916cf70>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
2023-09-23 23:19:15     ssl_sock = ssl_wrap_socket(
2023-09-23 23:19:15                └ <function ssl_wrap_socket at 0x7f17f91453f0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
2023-09-23 23:19:15     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
2023-09-23 23:19:15                │                     │     │        │           └ 'nyaa.si'
2023-09-23 23:19:15                │                     │     │        └ False
2023-09-23 23:19:15                │                     │     └ <ssl.SSLContext object at 0x7f17e940a040>
2023-09-23 23:19:15                │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
2023-09-23 23:19:15                └ <function _ssl_wrap_socket_impl at 0x7f17f91455a0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
2023-09-23 23:19:15     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2023-09-23 23:19:15            │           │           │                     └ 'nyaa.si'
2023-09-23 23:19:15            │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
2023-09-23 23:19:15            │           └ <function SSLContext.wrap_socket at 0x7f17fa425870>
2023-09-23 23:19:15            └ <ssl.SSLContext object at 0x7f17e940a040>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
2023-09-23 23:19:15     return self.sslsocket_class._create(
2023-09-23 23:19:15            │    │               └ <classmethod(<function SSLSocket._create at 0x7f17fa427400>)>
2023-09-23 23:19:15            │    └ <class 'ssl.SSLSocket'>
2023-09-23 23:19:15            └ <ssl.SSLContext object at 0x7f17e940a040>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
2023-09-23 23:19:15     self.do_handshake()
2023-09-23 23:19:15     │    └ <function SSLSocket.do_handshake at 0x7f17fa384700>
2023-09-23 23:19:15     └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
2023-09-23 23:19:15     self._sslobj.do_handshake()
2023-09-23 23:19:15     │    └ None
2023-09-23 23:19:15     └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
2023-09-23 23:19:15 
2023-09-23 23:19:15 ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 During handling of the above exception, another exception occurred:
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 Traceback (most recent call last):
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2023-09-23 23:19:15     response = self._make_request(
2023-09-23 23:19:15                │    └ <function HTTPConnectionPool._make_request at 0x7f17f91becb0>
2023-09-23 23:19:15                └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f17ee695de0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
2023-09-23 23:19:15     raise new_e
2023-09-23 23:19:15           └ SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)'))
2023-09-23 23:19:15 
2023-09-23 23:19:15 urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 The above exception was the direct cause of the following exception:
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 Traceback (most recent call last):
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2023-09-23 23:19:15     resp = conn.urlopen(
2023-09-23 23:19:15            │    └ <function HTTPConnectionPool.urlopen at 0x7f17f91bee60>
2023-09-23 23:19:15            └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f17ee695de0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-09-23 23:19:15     retries = retries.increment(
2023-09-23 23:19:15               │       └ <function Retry.increment at 0x7f17f931eb90>
2023-09-23 23:19:15               └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
2023-09-23 23:19:15     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-09-23 23:19:15           │             │      │    │            └ SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)'))
2023-09-23 23:19:15           │             │      │    └ SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)'))
2023-09-23 23:19:15           │             │      └ '/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91'
2023-09-23 23:19:15           │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f17ee695de0>
2023-09-23 23:19:15           └ <class 'urllib3.exceptions.MaxRetryError'>
2023-09-23 23:19:15 
2023-09-23 23:19:15 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nyaa.si', port=443): Max retries exceeded with url: /?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 During handling of the above exception, another exception occurred:
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 Traceback (most recent call last):
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 552, in deal_request
2023-09-23 23:19:15     else request.get_response_from_cached(save_cached=False)
2023-09-23 23:19:15          │       └ <function Request.get_response_from_cached at 0x7f17f074fd90>
2023-09-23 23:19:15          └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/network/request.py", line 517, in get_response_from_cached
2023-09-23 23:19:15     response_obj = self.get_response(save_cached=save_cached)
2023-09-23 23:19:15                    │    │                        └ False
2023-09-23 23:19:15                    │    └ <function Request.get_response at 0x7f17f074f6d0>
2023-09-23 23:19:15                    └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/network/request.py", line 396, in get_response
2023-09-23 23:19:15     response = self._session_downloader.download(self)
2023-09-23 23:19:15                │    │                            └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15                │    └ <property object at 0x7f17f0a0e3e0>
2023-09-23 23:19:15                └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/network/downloader/_requests.py", line 42, in download
2023-09-23 23:19:15     response = self._session.request(
2023-09-23 23:19:15                │    └ <property object at 0x7f17f0a0e750>
2023-09-23 23:19:15                └ <feapder.network.downloader._requests.RequestsSessionDownloader object at 0x7f17edbfe2c0>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2023-09-23 23:19:15     resp = self.send(prep, **send_kwargs)
2023-09-23 23:19:15            │    │    │       └ {'timeout': 22, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
2023-09-23 23:19:15            │    │    └ <PreparedRequest [GET]>
2023-09-23 23:19:15            │    └ <function Session.send at 0x7f17f8f58820>
2023-09-23 23:19:15            └ <requests.sessions.Session object at 0x7f17edbffac0>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2023-09-23 23:19:15     r = adapter.send(request, **kwargs)
2023-09-23 23:19:15         │       │    │          └ {'timeout': 22, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
2023-09-23 23:19:15         │       │    └ <PreparedRequest [GET]>
2023-09-23 23:19:15         │       └ <function HTTPAdapter.send at 0x7f17f8f47c70>
2023-09-23 23:19:15         └ <requests.adapters.HTTPAdapter object at 0x7f17ecff6500>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
2023-09-23 23:19:15     raise SSLError(e, request=request)
2023-09-23 23:19:15           │                   └ <PreparedRequest [GET]>
2023-09-23 23:19:15           └ <class 'requests.exceptions.SSLError'>
2023-09-23 23:19:15 
2023-09-23 23:19:15 requests.exceptions.SSLError: HTTPSConnectionPool(host='nyaa.si', port=443): Max retries exceeded with url: /?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 During handling of the above exception, another exception occurred:
2023-09-23 23:19:15 
2023-09-23 23:19:15 
2023-09-23 23:19:15 Traceback (most recent call last):
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
2023-09-23 23:19:15     self._bootstrap_inner()
2023-09-23 23:19:15     │    └ <function Thread._bootstrap_inner at 0x7f17fb23fe20>
2023-09-23 23:19:15     └ <AirSpiderParserControl(Thread-700, started daemon 139740595047216)>
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-09-23 23:19:15     self.run()
2023-09-23 23:19:15     │    └ <function AirSpiderParserControl.run at 0x7f17f068c4c0>
2023-09-23 23:19:15     └ <AirSpiderParserControl(Thread-700, started daemon 139740595047216)>
2023-09-23 23:19:15 
2023-09-23 23:19:15 > File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 487, in run
2023-09-23 23:19:15     self.deal_request(request)
2023-09-23 23:19:15     │    │            └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15     │    └ <function AirSpiderParserControl.deal_request at 0x7f17f068c550>
2023-09-23 23:19:15     └ <AirSpiderParserControl(Thread-700, started daemon 139740595047216)>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 617, in deal_request
2023-09-23 23:19:15     request.del_proxy()
2023-09-23 23:19:15     │       └ <function Request.del_proxy at 0x7f17f074f910>
2023-09-23 23:19:15     └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/network/request.py", line 431, in del_proxy
2023-09-23 23:19:15     proxy = self.get_proxy()
2023-09-23 23:19:15             │    └ <function Request.get_proxy at 0x7f17f074f880>
2023-09-23 23:19:15             └ <Request https://nyaa.si/?f=0&c=0_0&q=%E5%A0%80%E4%B8%8E%E5%AE%AB%E6%9D%91>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/nas-tools/third_party/feapder/feapder/network/request.py", line 426, in get_proxy
2023-09-23 23:19:15     return re.sub(
2023-09-23 23:19:15            │  └ <function sub at 0x7f17fb223640>
2023-09-23 23:19:15            └ <module 're' from '/usr/local/lib/python3.10/re.py'>
2023-09-23 23:19:15 
2023-09-23 23:19:15   File "/usr/local/lib/python3.10/re.py", line 209, in sub
2023-09-23 23:19:15     return _compile(pattern, flags).sub(repl, string, count)
2023-09-23 23:19:15            │        │        │          │     │       └ 0
2023-09-23 23:19:15            │        │        │          │     └ None
2023-09-23 23:19:15            │        │        │          └ ''
2023-09-23 23:19:15            │        │        └ 0
2023-09-23 23:19:15            │        └ 'http.*?//'
2023-09-23 23:19:15            └ <function _compile at 0x7f17fb223b50>
2023-09-23 23:19:15 
2023-09-23 23:19:15 TypeError: expected string or bytes-like object
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     AutoSignIn.sign_in (trigger: interval[8:00:00], pending)
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     IYUUAutoSeed.auto_seed (trigger: cron[month='*', day='*', day_of_week='*', hour='22', minute='0'], pending)
2023-09-23 23:19:20     IYUUAutoSeed.check_recheck (trigger: interval[0:03:00], pending)
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     AutoBackup.__backup (trigger: cron[month='*', day='*', day_of_week='*', hour='23', minute='0'], pending)
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     AutoSignIn.sign_in (trigger: interval[8:00:00], pending)
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     IYUUAutoSeed.auto_seed (trigger: cron[month='*', day='*', day_of_week='*', hour='22', minute='0'], pending)
2023-09-23 23:19:20     IYUUAutoSeed.check_recheck (trigger: interval[0:03:00], pending)
2023-09-23 23:19:20 Pending jobs:
2023-09-23 23:19:20     AutoBackup.__backup (trigger: cron[month='*', day='*', day_of_week='*', hour='23', minute='0'], pending)

**Comment by iovejieba** [comment]
> ~不确定有没有关系,还遇到这个问题 关于openssl, 这个发生在搜索资源的时候~ 破案了,我的路由器block了nyaa...

倒也不是....无法访问的报错和这个貌似不一样  acg现在好像标题返回有改动  也是argument of type 'NoneType' is not iterable  但nyaa 貌似没问题
