### ISSUE TITLE
[错误报告]: 签到无通知

### ISSUE THREAD

**Issue by hxpcnz** [hsuyelin/nas-tools#354]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

插件问题

### 问题描述

签到插件无通知，运行日志显示正常运行，消息中心内没有看到有通知。确定已选择运行通知选项

### 发生问题时系统日志和配置文件

```bash
21:50:45		
站点自动签到 - 签到服务启动，立即运行一次
21:50:45		
站点自动签到 - 定时签到服务启动，周期：0 0 * * *
21:50:48		
站点自动签到 - 今日 2023-10-02 未签到，开始签到已选站点
21:50:48		
站点自动签到 - 开始执行签到任务
```

**Comment by iovejieba** [comment]
看容器日志 是否有报错

**Comment by hxpcnz** [comment]
2023/10/3 9:08:23::ffff:223.108.25.138 - - [03/Oct/2023 09:08:23] code 400, message Bad request syntax ('SSH-2.0-OpenSSH')2023/10/3 9:08:14UnboundLocalError: local variable 'site_id' referenced before assignment2023/10/3 9:08:14_result = {'id': site_id, 'date': s[1], 'name': site_names[0], 'signurl': s[2], 'result': status }2023/10/3 9:08:14File "/nas-tools/app/plugins/modules/autosignin.py", line 565, in sign_in2023/10/3 9:08:14retval = job.func(*job.args, **job.kwargs)2023/10/3 9:08:14File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job2023/10/3 9:08:14Traceback (most recent call last):2023/10/3 9:08:14Job "AutoSignIn.sign_in (trigger: date[2023-10-03 09:08:12 CST], next run at: 2023-10-03 09:08:12 CST)" raised an exception2023/10/3 9:08:142023-10-03 09:08:14,558 INFO: 【Plugin】站点自动签到 - 站点签到任务完成！发自我的手机-------- 原始邮件 --------发件人： iovejieba ***@***.***>日期： 2023年10月3日周二 凌晨1:53收件人： hsuyelin/nas-tools ***@***.***>抄送： 砖头 ***@***.***>, Author ***@***.***>主    题： Re: [hsuyelin/nas-tools] [错误报告]: 签到无通知 (Issue #354)
看容器日志 是否有报错

**Comment by iovejieba** [comment]
> 2023/10/3 9:08:23::ffff:223.108.25.138 - - [03/Oct/2023 09:08:23] code 400, message Bad request syntax ('SSH-2.0-OpenSSH')2023/10/3 9:08:14UnboundLocalError: local variable 'site_id' referenced before assignment2023/10/3 9:08:14_result = {'id': site_id, 'date': s[1], 'name': site_names[0], 'signurl': s[2], 'result': status }2023/10/3 9:08:14File "/nas-tools/app/plugins/modules/autosignin.py", line 565, in sign_in2023/10/3 9:08:14retval = job.func(*job.args, **job.kwargs)2023/10/3 9:08:14File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job2023/10/3 9:08:14Traceback (most recent call last):2023/10/3 9:08:14Job "AutoSignIn.sign_in (trigger: date[2023-10-03 09:08:12 CST], next run at: 2023-10-03 09:08:12 CST)" raised an exception2023/10/3 9:08:142023-10-03 09:08:14,558 INFO: 【Plugin】站点自动签到 - 站点签到任务完成！发自我的手机-------- 原始邮件 --------发件人： iovejieba ***@***.***>日期： 2023年10月3日周二 凌晨1:53收件人： hsuyelin/nas-tools ***@***.***>抄送： 砖头 ***@***.***>, Author ***@***.***>主 题： Re: [hsuyelin/nas-tools] [错误报告]: 签到无通知 (Issue #354) 看容器日志 是否有报错 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

是不是和我一样前几个版本一致github拉更新没拉容器...  我没拉容器更新 自签也是这样 不过一直没用签到

**Comment by Meteor2017** [comment]
而且还有一个情况，卸载和安装自动签到插件完全失效了，签到插件自始至终都在后台显示着

**Comment by chuan1127** [comment]
2023-10-10 10:24:32,254 INFO: 【Plugin】站点自动签到 - 签到服务启动，立即运行一次
2023-10-10 10:24:32,279 INFO: 【Plugin】站点自动签到 - 定时签到服务启动，周期：0 */2 * * *
2023-10-10 10:24:32,280 INFO: 【Plugin】站点自动签到 - 漏签检测服务启动，检测时段：08:00-23:59
2023-10-10 10:24:32,283 INFO: 【Plugin】站点自动签到 - 漏签检测服务启动，即将进行补签！
2023-10-10 10:24:32,284 INFO: 【Plugin】站点自动签到 - 下一次检测时间：11:06:01
2023-10-10 10:24:32,286 DEBUG: 生效插件配置：AutoSignIn
2023-10-10 10:24:35,264 INFO: 【Plugin】站点自动签到 - 今日 2023-10-10 未签到，开始签到已选站点
2023-10-10 10:24:35,264 INFO: 【Plugin】站点自动签到 - 开始执行签到任务
2023-10-10 10:24:35,287 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://hdmayi.com/index.php
2023-10-10 10:24:35,288 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://piggo.me/index.php
2023-10-10 10:24:35,291 INFO: 【Plugin】站点自动签到 - 今日 2023-10-10 未签到，开始签到已选站点
2023-10-10 10:24:35,291 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://kp.m-team.cc/index.php
2023-10-10 10:24:35,295 INFO: 【Plugin】站点自动签到 - 开始执行签到任务
2023-10-10 10:24:35,318 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://piggo.me/index.php
2023-10-10 10:24:35,321 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://hdmayi.com/index.php
2023-10-10 10:24:35,321 INFO: 【Plugin】站点自动签到 - 开始站点模拟登录：https://kp.m-team.cc/index.php
2023-10-10 10:24:36,578 INFO: 【Plugin】站点自动签到 - https://piggo.me/index.php 模拟登录成功
2023-10-10 10:24:36,770 INFO: 【Plugin】站点自动签到 - https://kp.m-team.cc/index.php 模拟登录成功
2023-10-10 10:24:36,800 INFO: 【Plugin】站点自动签到 - https://kp.m-team.cc/index.php 模拟登录成功
2023-10-10 10:24:36,876 INFO: 【Plugin】站点自动签到 - https://piggo.me/index.php 模拟登录成功
2023-10-10 10:24:37,147 INFO: 【Plugin】站点自动签到 - https://hdmayi.com/index.php 模拟登录成功
2023-10-10 10:24:37,155 INFO: 【Plugin】站点自动签到 - 站点签到任务完成！
Job "AutoSignIn.sign_in (trigger: date[2023-10-10 10:24:35 CST], next run at: 2023-10-10 10:24:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/plugins/modules/autosignin.py", line 565, in sign_in
    _result = {'id': site_id, 'date': s[1], 'name': site_names[0], 'signurl': s[2], 'result': status }
UnboundLocalError: local variable 'site_id' referenced before assignment
2023-10-10 10:24:37,344 INFO: 【Plugin】站点自动签到 - https://hdmayi.com/index.php 模拟登录成功
2023-10-10 10:24:37,352 INFO: 【Plugin】站点自动签到 - 站点签到任务完成！
Job "AutoSignIn.sign_in (trigger: date[2023-10-10 10:24:35 CST], next run at: 2023-10-10 10:24:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/plugins/modules/autosignin.py", line 565, in sign_in
    _result = {'id': site_id, 'date': s[1], 'name': site_names[0], 'signurl': s[2], 'result': status }
UnboundLocalError: local variable 'site_id' referenced before assignment
我的签到也是这样的报错
