### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by chuan1127** [hsuyelin/nas-tools#364]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

主程序运行问题

### 问题描述

刷流提示正常启动，但是获取不到SSR里的种子。

### 发生问题时系统日志和配置文件

```bash
2023-10-07 09:09:11,386 INFO: 3 个刷流服务正常启动
2023-10-07 09:09:17,530 INFO: 3 个刷流服务正常启动
2023-10-07 09:09:21,676 INFO: 3 个刷流服务正常启动
2023-10-07 09:10:47,942 INFO: 3 个刷流服务正常启动
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
2023-10-07 09:10:56,485 INFO: 3 个刷流服务正常启动
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int
'in <string>' requires string as left operand, not int

Exception: The resource you requested could not be found.
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/media/scraper.py", line 661, in gen_scraper_files
    episode_image = self.media.get_episode_images(tv_id=media.tmdb_id,
  File "/nas-tools/app/media/media.py", line 2319, in get_episode_images
    res = self.episode.images(tv_id, season_id, episode_id)
  File "/nas-tools/app/media/tmdbv3api/objs/episode.py", line 18, in images
    return self._get_obj(
  File "/nas-tools/app/media/tmdbv3api/tmdb.py", line 138, in _get_obj
    raise TMDbException(result["status_message"])
app.media.tmdbv3api.exceptions.TMDbException: The resource you requested could not be found.


Pending jobs:
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
Pending jobs:
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
Pending jobs:
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
Pending jobs:
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.check_task_rss (trigger: interval[0:30:00], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
2023-10-07 09:11:01,771 INFO: 3 个刷流服务正常启动
```

**Comment by iovejieba** [comment]
你得说是具体哪个站的rss....

**Comment by chuan1127** [comment]
馒头，猪猪，蚂蚁，都获取不到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsuyelin/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月7日(星期六) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsuyelin/nas-tools] [错误报告]: 刷流提示正常启动，但是获取不到SSR里的种子。 (Issue #364)





 
你得说是具体哪个站的rss....

**Comment by iovejieba** [comment]
> 馒头，猪猪，蚂蚁，都获取不到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hsuyelin/nas-tools" ***@***.***&gt;; 发送时间:&nbsp;2023年10月7日(星期六) 中午12:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hsuyelin/nas-tools] [错误报告]: 刷流提示正常启动，但是获取不到SSR里的种子。 (Issue #364) 你得说是具体哪个站的rss.... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个非常可能是你个人情况，建议拉容器更新下看看，mt，icy，hdfans exo，我这边均正常另外rss勾选分类的时候我建议只选大分类其他别选择否则rss订阅页容易保utf8错误
