### ISSUE TITLE
一堆日志看不懂，

### ISSUE THREAD

**Issue by chuan1127** [hsuyelin/nas-tools#372]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

其他问题

### 问题描述

每次都会有这样的日志出现，不知道是啥原因.

### 发生问题时系统日志和配置文件

```bash
File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 552, in deal_request
    else request.get_response_from_cached(save_cached=False)
         │       └ <function Request.get_response_from_cached at 0x154dcd2c5fc0>
         └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 517, in get_response_from_cached
    response_obj = self.get_response(save_cached=save_cached)
                   │    │                        └ False
                   │    └ <function Request.get_response at 0x154dcd2c5900>
                   └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 396, in get_response
    response = self._session_downloader.download(self)
               │    │                            └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>
               │    └ <property object at 0x154dcd7e1080>
               └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>

  File "/nas-tools/third_party/feapder/feapder/network/downloader/_requests.py", line 42, in download
    response = self._session.request(
               │    └ <property object at 0x154dcd7e1490>
               └ <feapder.network.downloader._requests.RequestsSessionDownloader object at 0x154dcb57d1e0>

  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 22, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x154dd541bf40>
           └ <requests.sessions.Session object at 0x154dcb57fa30>
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 22, 'proxies': OrderedDict(), 'stream': True, 'verify': False, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x154dd541b400>
        └ <requests.adapters.HTTPAdapter object at 0x154dcb57c2b0>
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='acg.rip', port=443): Max retries exceeded with url: /?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x154dd76b80d0>
    └ <AirSpiderParserControl(Thread-60914, started daemon 23422411279152)>
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function AirSpiderParserControl.run at 0x154dcd2c6680>
    └ <AirSpiderParserControl(Thread-60914, started daemon 23422411279152)>

> File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 487, in run
    self.deal_request(request)
    │    │            └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>
    │    └ <function AirSpiderParserControl.deal_request at 0x154dcd2c6710>
    └ <AirSpiderParserControl(Thread-60914, started daemon 23422411279152)>

  File "/nas-tools/third_party/feapder/feapder/core/parser_control.py", line 617, in deal_request
    request.del_proxy()
    │       └ <function Request.del_proxy at 0x154dcd2c5b40>
    └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 431, in del_proxy
    proxy = self.get_proxy()
            │    └ <function Request.get_proxy at 0x154dcd2c5ab0>
            └ <Request https://acg.rip/?term=%E6%81%8B%E7%88%B1%E5%90%A7%20%E5%AF%A8%E4%B8%BB>

  File "/nas-tools/third_party/feapder/feapder/network/request.py", line 426, in get_proxy
    return re.sub(
           │  └ <function sub at 0x154dd7683880>
           └ <module 're' from '/usr/local/lib/python3.10/re.py'>

  File "/usr/local/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           │        │        │          │     │       └ 0
           │        │        │          │     └ None
           │        │        │          └ ''
           │        │        └ 0
           │        └ 'http.*?//'
           └ <function _compile at 0x154dd7683d90>
```

**Comment by iovejieba** [comment]
你内置索引选了acg.rip   但你网络无法访问acg.rip...就这个报错，辅助线路加持就没事了或者不用acg

**Comment by hsuyelin** [comment]
这个是连不上acg.rip导致的，建议使用魔法
