### ISSUE TITLE
[错误报告]: 下载器限速插件不生效

### ISSUE THREAD

**Issue by jiezaizone** [hsuyelin/nas-tools#434]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.11

### 问题类型

Docker或运行环境问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/28976666/3b472dc0-5e69-435b-8512-58e0848e704f)
![image](https://github.com/hsuyelin/nas-tools/assets/28976666/916374c6-7586-4ccb-a0c9-95a01d5d9bb5)

<img width="983" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/28976666/9218a5c0-ab3b-43f4-99fe-221c052c96b0">
<img width="1444" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/28976666/b90e0d11-c434-4556-b63a-136e3a0495f5">
如截图所示，配置了下载器限速插件，显示是启动状态，看日志也是有加载限速插件的。然后plex播放时候，限速插件没有生效，即没有发送限速插件通知，查看下载器也没有限速。查看日志，有接收到plex的webhook事件的，暂停播放通知也有推送，就是生效不了限速。plex播放器是外网播放的

### 发生问题时系统日志和配置文件

```bash
Pending jobs:
    AutoSignIn.sign_in (trigger: cron[hour='8', minute='10'], pending)
    AutoSignIn.check_missed_signs (trigger: date[2023-11-10 08:38:02 CST], pending)
2023-11-09 18:20:22,407	INFO: 加载插件：<class 'app.plugins.modules.autosignin.AutoSignIn'>
2023-11-09 18:20:22,408	INFO: 加载插件：<class 'app.plugins.modules.opensubtitles.OpenSubtitles'>
Pending jobs:
    SpeedLimiter.__check_playing_sessions (trigger: interval[0:05:00], pending)
2023-11-09 18:20:22,419	INFO: 【Plugin】下载器限速 - 播放限速服务启动
2023-11-09 18:20:22,420	INFO: 加载插件：<class 'app.plugins.modules.speedlimiter.SpeedLimiter'>
2023-11-09 18:20:22,420	INFO: 加载插件：<class 'app.plugins.modules.torrentremover.TorrentRemover'>
2023-11-09 18:20:22,420	INFO: 【Plugin】种子标记 - 标记服务启动，周期：0 8 * * *
Pending jobs:
    TorrentMark.auto_mark (trigger: cron[month='*', day='*', day_of_week='*', hour='8', minute='0'], pending)
2023-11-09 18:20:22,422	INFO: 加载插件：<class 'app.plugins.modules.torrentmark.TorrentMark'>
2023-11-09 18:20:22,422	INFO: 加载插件：<class 'app.plugins.modules.customhosts.CustomHosts'>
2023-11-09 18:20:22,422	INFO: 加载插件：<class 'app.plugins.modules.diskspacesaver.DiskSpaceSaver'>
2023-11-09 18:20:22,568	INFO: 加载插件：<class 'app.plugins.modules.jackett.Jackett'>
2023-11-09 18:20:22,570	INFO: 【Plugin】豆瓣同步 - 豆瓣全量同步服务启动，周期：6 小时，类型：['do', 'wish', 'collect']，用户：['141620136']
Pending jobs:
    DoubanSync.sync (trigger: interval[6:00:00], pending)
2023-11-09 18:20:22,571	INFO: 加载插件：<class 'app.plugins.modules.doubansync.DoubanSync'>
2023-11-09 18:20:22,572	INFO: 【Plugin】IYUU自动辅种 - 辅种服务启动，周期：10 10 */2 * *
Pending jobs:
    IYUUAutoSeed.auto_seed (trigger: cron[month='*', day='*/2', day_of_week='*', hour='10', minute='10'], pending)
    IYUUAutoSeed.check_recheck (trigger: interval[0:03:00], pending)
2023-11-09 18:20:22,574	INFO: 加载插件：<class 'app.plugins.modules.iyuuautoseed.IYUUAutoSeed'>
2023-11-09 18:20:22,575	INFO: 【Plugin】自动转移做种 - 移转做种服务启动，周期：1 1 */5 * *
Pending jobs:
    TorrentTransfer.transfer (trigger: cron[month='*', day='*/5', day_of_week='*', hour='1', minute='1'], pending)
    TorrentTransfer.check_recheck (trigger: interval[0:03:00], pending)
2023-11-09 18:20:22,577	INFO: 加载插件：<class 'app.plugins.modules.torrenttransfer.TorrentTransfer'>
2023-11-09 18:20:25,690	INFO: 【Plugin】CookieCloud同步 - 同步服务启动，周期：1 1 */3 * *
Pending jobs:
    CookieCloud.__cookie_sync (trigger: cron[month='*', day='*/3', day_of_week='*', hour='1', minute='1'], pending)
2023-11-09 18:20:25,696	INFO: 加载插件：<class 'app.plugins.modules.cookiecloud.CookieCloud'>
2023-11-09 18:20:25,697	INFO: 【Plugin】自动备份 - 定时备份服务启动，周期：2 2 */2 * *
Pending jobs:
    AutoBackup.__backup (trigger: cron[month='*', day='*/2', day_of_week='*', hour='2', minute='2'], pending)
2023-11-09 18:20:25,699	INFO: 加载插件：<class 'app.plugins.modules.autobackup.AutoBackup'>
 * Serving Flask app 'web.main'
 * Debug mode: on
s6-rc: info: service svc-nastools successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-09 18:21:51,482	INFO: Challenge not detected!
2023-11-09 18:21:59,688	INFO: Challenge not detected!
2023-11-09 18:22:14,736	INFO: 处理事件：plex.webhook - [<function SpeedLimiter.plex_action at 0x7f84eacdfac0>, <function Webhook.send at 0x7f84eacf20e0>]
(401) unauthorized; http://192.168.4.37:32400/status/sessions <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html> Traceback (most recent call last):
  File "/nas-tools/app/plugins/plugin_manager.py", line 133, in run_plugin
    return getattr(self._running_plugins[pid], method)(*args, **kwargs)
  File "/nas-tools/app/plugins/modules/speedlimiter.py", line 366, in plex_action
    self.__check_playing_sessions(_mediaserver_type=MediaServerType.PLEX, time_check=False)
  File "/nas-tools/app/plugins/modules/speedlimiter.py", line 379, in __check_playing_sessions
    playing_sessions = self._mediaserver.get_playing_sessions()
  File "/nas-tools/app/mediaserver/media_server.py", line 346, in get_playing_sessions
    return self.server.get_playing_sessions()
  File "/nas-tools/app/mediaserver/client/plex.py", line 498, in get_playing_sessions
    sessions = self._plex.sessions()
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 805, in sessions
    return self.fetchItems('/status/sessions')
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 255, in fetchItems
    data = self._server.query(ekey, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 753, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; http://192.168.4.37:32400/status/sessions <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>

2023-11-09 18:22:21,513	INFO: Challenge not detected!
2023-11-09 18:22:35,673	INFO: Challenge not detected!
Message: timeout: Timed out receiving message from renderer: 23.523
  (Session info: chrome=117.0.5938.62)
```

**Comment by Travisss** [comment]
我也有同样的问题，版本是3.3.12。日志里的输出信息都是正确的，有改变限速的提示，但是qb限速没有变化
