### ISSUE TITLE
[错误报告]: [Errno 2] No such file or directory: 'ffprobe'

### ISSUE THREAD

**Issue by huangmengsheng** [hsuyelin/nas-tools#440]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.12

### 问题类型

其他问题

### 问题描述

同步目录时出现的错误

### 发生问题时系统日志和配置文件

```bash
2023-11-14 17:29:08,998	INFO: 【Meta】未能获取到视频元信息
2023-11-14 17:29:09,050	INFO: 【Meta】正在查询TMDB电视剧：25080 ...
2023-11-14 17:29:09,051	INFO: 【Meta】25080 查询结果：中华小当家
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
[Errno 2] No such file or directory: 'ffprobe'
2023-11-14 17:29:09,052	INFO: 【Meta】未能获取到视频元信息
2023-11-14 17:29:09,103	INFO: 【Meta】正在查询TMDB电视剧：25080 ...
2023-11-14 17:29:09,104	INFO: 【Meta】25080 查询结果：中华小当家
2023-11-14 17:29:09,105	INFO: 【Meta】未能获取到视频元信息
```

**Comment by huangmengsheng** [comment]
Traceback (most recent call last):
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/volume2/@appstore/NASTool/nas-tools/web/main.py", line 1042, in plugin
    Plugins = WebAction().get_plugins_conf().get("result")
  File "/volume2/@appstore/NASTool/nas-tools/web/action.py", line 5251, in get_plugins_conf
    Plugins = PluginManager().get_plugins_conf(current_user.level)
  File "/volume2/@appstore/NASTool/nas-tools/app/plugins/plugin_manager.py", line 250, in get_plugins_conf
    title, _, _ = plugin.get_page()
  File "/volume2/@appstore/NASTool/nas-tools/app/plugins/modules/media_library_archive.py", line 436, in get_page
    archive_files = self.__get_archive_files() or []
  File "/volume2/@appstore/NASTool/nas-tools/app/plugins/modules/media_library_archive.py", line 505, in __get_archive_files
    file_names = os.listdir(archive_path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/packages/NASTool/target/config/archive_file/media_library'

**Comment by huangmengsheng** [comment]
2023-11-14 17:09:28,644 WARN exited: nas-tools (terminated by SIGKILL; not expected)
2023-11-14 17:09:29,706 INFO spawned: 'nas-tools' with pid 13207
2023-11-14 17:09:34,712 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-14 17:12:15,140 WARN exited: nas-tools (terminated by SIGKILL; not expected)
2023-11-14 17:12:16,141 INFO spawned: 'nas-tools' with pid 15164
2023-11-14 17:12:21,192 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2023-11-14 17:18:47,945 WARN exited: nas-tools (terminated by SIGKILL; not expected)
2023-11-14 17:18:48,950 INFO spawned: 'nas-tools' with pid 18113
2023-11-14 17:18:53,964 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

**Comment by hsuyelin** [comment]
群晖的版本请咨询打包群晖的开发人员，我这边只提供docker
