### ISSUE TITLE
[错误报告]: 无法打开插件菜单

### ISSUE THREAD

**Issue by naoki66** [hsuyelin/nas-tools#449]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.12 f74a3c9

### 问题类型

主程序运行问题

### 问题描述

无法打开插件菜单，仅仅添加了[【媒体库归档】插件]   ，再重启就无法打开

### 发生问题时系统日志和配置文件

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1042, in plugin
    Plugins = WebAction().get_plugins_conf().get("result")
  File "/nas-tools/web/action.py", line 5251, in get_plugins_conf
    Plugins = PluginManager().get_plugins_conf(current_user.level)
  File "/nas-tools/app/plugins/plugin_manager.py", line 250, in get_plugins_conf
    title, _, _ = plugin.get_page()
  File "/nas-tools/app/plugins/modules/media_library_archive.py", line 436, in get_page
    archive_files = self.__get_archive_files() or []
  File "/nas-tools/app/plugins/modules/media_library_archive.py", line 505, in __get_archive_files
    file_names = os.listdir(archive_path)
FileNotFoundError: [Errno 2] No such file or directory: '/config/archive_file/media_library'
```

**Comment by huluohu** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> v3.3.12 [f74a3c9](https://github.com/hsuyelin/nas-tools/commit/f74a3c9acf491171ea7d4be6700bb32f9e3878ea)
> 
> ### 问题类型
> 主程序运行问题
> 
> ### 问题描述
> 无法打开插件菜单，仅仅添加了[【媒体库归档】插件] ，再重启就无法打开
> 
> ### 发生问题时系统日志和配置文件
> ```shell
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
>     return self.app(environ, start_response)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
>     return original_handler(e)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
>     return original_handler(e)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
>     return current_app.ensure_sync(func)(*args, **kwargs)
>   File "/nas-tools/web/main.py", line 1042, in plugin
>     Plugins = WebAction().get_plugins_conf().get("result")
>   File "/nas-tools/web/action.py", line 5251, in get_plugins_conf
>     Plugins = PluginManager().get_plugins_conf(current_user.level)
>   File "/nas-tools/app/plugins/plugin_manager.py", line 250, in get_plugins_conf
>     title, _, _ = plugin.get_page()
>   File "/nas-tools/app/plugins/modules/media_library_archive.py", line 436, in get_page
>     archive_files = self.__get_archive_files() or []
>   File "/nas-tools/app/plugins/modules/media_library_archive.py", line 505, in __get_archive_files
>     file_names = os.listdir(archive_path)
> FileNotFoundError: [Errno 2] No such file or directory: '/config/archive_file/media_library'
> ```

到/config 目录下创建archive_file/media_library目录就好了。

**Comment by hotlcc** [comment]
问题已修复，手动更新即可：
<img width="198" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/14865895/8c501ca9-6a11-4627-92bf-cd33b2cdfe0c">

**Comment by Aquede** [comment]
> 问题已修复，手动更新即可： <img alt="image" width="198" src="https://user-images.githubusercontent.com/14865895/283839525-8c501ca9-6a11-4627-92bf-cd33b2cdfe0c.png">

为什么我的右上角没有更新这个按钮

**Comment by luotao21** [comment]
使用最新的docker版[v3.3.12 f74a3c9]，故障依旧。

**Comment by naoki66** [comment]
<html>
<body>

2023/11/22 23:58:32 | stdout | RuntimeError: cannot schedule new futures after shutdown
-- | -- | --
2023/11/22 23:58:32 | stdout | raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/22 23:58:32 | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/22 23:58:32 | stdout | f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/22 23:58:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/22 23:58:32 | stdout | self._do_submit_job(job, run_times)
2023/11/22 23:58:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/22 23:58:32 | stdout | executor.submit_job(job, run_times)
2023/11/22 23:58:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/22 23:58:32 | stdout | Traceback (most recent call last):
2023/11/22 23:58:32 | stdout | Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-22 23:58:32 CST)" to executor "default"
2023/11/22 23:57:32 | stdout | RuntimeError: cannot schedule new futures after shutdown
2023/11/22 23:57:32 | stdout | raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/22 23:57:32 | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/22 23:57:32 | stdout | f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/22 23:57:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/22 23:57:32 | stdout | self._do_submit_job(job, run_times)
2023/11/22 23:57:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/22 23:57:32 | stdout | executor.submit_job(job, run_times)
2023/11/22 23:57:32 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/22 23:57:32 | stdout | Traceback (most recent call last):
2023/11/22 23:57:32 | stdout | Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-22 23:57:32 CST)" to executor "default"
2023/11/22 23:57:31 | stdout | RuntimeError: cannot schedule new futures after shutdown
2023/11/22 23:57:31 | stdout | raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/22 23:57:31 | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/22 23:57:31 | stdout | f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/22 23:57:31 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/22 23:57:31 | stdout | self._do_submit_job(job, run_times)
2023/11/22 23:57:31 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/22 23:57:31 | stdout | executor.submit_job(job, run_times)
2023/11/22 23:57:31 | stdout | File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/22 23:57:31 | stdout | Traceback (most recent call last):
2023/11/22 23:57:31 | stdout | Error submitting job "SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-11-22 23:57:31 CST)" to executor "default"
2023/11/22 23:56:32 | stdout | AttributeError: 'TORRENTREMOVETASK' object has no attribute 'ONLYNASTOOL'. Did you mean: 'ONLY_NASTOOL'?
2023/11/22 23:56:32 | stdout | "onlynastool": task.ONLYNASTOOL,
2023/11/22 23:56:32 | stdout | File "/nas-tools/app/torrentremover.py", line 56, in init_config
2023/11/22 23:56:32 | stdout | self.init_config()
2023/11/22 23:56:32 | stdout | File "/nas-tools/app/torrentremover.py", line 28, in __init__
2023/11/22 23:56:32 | stdout | INSTANCES[cls] = cls(*args, **kwargs)
2023/11/22 23:56:32 | stdout | File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023/11/22 23:56:32 | stdout | TorrentRemover()
2023/11/22 23:56:32 | stdout | File "/nas-tools/web/action.py", line 336, in start_service
2023/11/22 23:56:32 | stdout | WebAction.start_service()
2023/11/22 23:56:32 | stdout | File "/nas-tools/run.py", line 105, in start_service
2023/11/22 23:56:32 | stdout | start_service()
2023/11/22 23:56:32 | stdout | File "/nas-tools/run.py", line 114, in <module>
2023/11/22 23:56:32 | stdout | Traceback (most recent call last):
2023/11/22 23:56:32 | stdout | 2023-11-22 23:56:32,973 INFO: 1 个刷流服务正常启动
2023/11/22 23:56:32 | stdout | BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
2023/11/22 23:56:32 | stdout | BrushTask.check_task_rss (trigger: interval[0:20:00], pending)
2023/11/22 23:56:32 | stdout | Pending jobs:
2023/11/22 23:56:32 | stdout | get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-11-22 23:56:32 CST)
2023/11/22 23:56:32 | stdout | MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
2023/11/22 23:56:32 | stdout | Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
2023/11/22 23:56:32 | stdout | Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
2023/11/22 23:56:32 | stdout | Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
2023/11/22 23:56:32 | stdout | MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
2023/11/22 23:56:32 | stdout | MediaServer.sync_mediaserver (trigger: interval[8:00:00], pending)
2023/11/22 23:56:32 | stdout | Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
2023/11/22 23:56:32 | stdout | Rss.rssdownload (trigger: interval[0:33:20], pending)
2023/11/22 23:56:32 | stdout | SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-11-22 23:57:31 CST)
2023/11/22 23:56:32 | stdout | Pending jobs:


</body>
</html>

**Comment by naoki66** [comment]
docker情况下 有没有办法删除插件
Traceback (most recent call last):
  File "/nas-tools/run.py", line 114, in <module>
    start_service()
  File "/nas-tools/run.py", line 105, in start_service
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 336, in start_service
    TorrentRemover()
  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/torrentremover.py", line 28, in __init__
    self.init_config()
  File "/nas-tools/app/torrentremover.py", line 56, in init_config
    "onlynastool": task.ONLYNASTOOL,
AttributeError: 'TORRENTREMOVETASK' object has no attribute 'ONLYNASTOOL'. Did you mean: 'ONLY_NASTOOL'?
似乎最近的BUG都是新插件造成的
