### ISSUE TITLE
[错误报告]: 下载器助手和删种--导致程序无法运行

### ISSUE THREAD

**Issue by naoki66** [hsuyelin/nas-tools#465]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

ca99356bf3ce6a290c026252fc8f8af27a88dc47

### 问题类型

主程序运行问题

### 问题描述

commit/3ab9e3b9d34de57f988f301ccbb35f127e455130未成功修复
无法启动，web3000无法访问
日志卡在raise RuntimeError('cannot schedule new futures after shutdown')

### 发生问题时系统日志和配置文件

```bash
+ f74a3c9...ca99356 master     -> origin/master  (forced update)
HEAD is now at ca99356 fix(sync): 启动目录同步时，如果目的目录存在无需再次创建
------

date	stream	content
2023/11/23 00:24:00	stdout	RuntimeError: cannot schedule new futures after shutdown
2023/11/23 00:24:00	stdout	    raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/23 00:24:00	stdout	  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/23 00:24:00	stdout	    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/23 00:24:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/23 00:24:00	stdout	    self._do_submit_job(job, run_times)
2023/11/23 00:24:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/23 00:24:00	stdout	    executor.submit_job(job, run_times)
2023/11/23 00:24:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/23 00:24:00	stdout	Traceback (most recent call last):
2023/11/23 00:24:00	stdout	Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-23 00:24:00 CST)" to executor "default"
2023/11/23 00:23:00	stdout	RuntimeError: cannot schedule new futures after shutdown
2023/11/23 00:23:00	stdout	    raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/23 00:23:00	stdout	  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/23 00:23:00	stdout	    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/23 00:23:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/23 00:23:00	stdout	    self._do_submit_job(job, run_times)
2023/11/23 00:23:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/23 00:23:00	stdout	    executor.submit_job(job, run_times)
2023/11/23 00:23:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/23 00:23:00	stdout	Traceback (most recent call last):
2023/11/23 00:23:00	stdout	Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-23 00:23:00 CST)" to executor "default"
2023/11/23 00:22:00	stdout	RuntimeError: cannot schedule new futures after shutdown
2023/11/23 00:22:00	stdout	    raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/23 00:22:00	stdout	  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/23 00:22:00	stdout	    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/23 00:22:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/23 00:22:00	stdout	    self._do_submit_job(job, run_times)
2023/11/23 00:22:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/23 00:22:00	stdout	    executor.submit_job(job, run_times)
2023/11/23 00:22:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/23 00:22:00	stdout	Traceback (most recent call last):
2023/11/23 00:22:00	stdout	Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-23 00:22:00 CST)" to executor "default"
2023/11/23 00:21:00	stdout	RuntimeError: cannot schedule new futures after shutdown
2023/11/23 00:21:00	stdout	    raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/23 00:21:00	stdout	  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/23 00:21:00	stdout	    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/23 00:21:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/23 00:21:00	stdout	    self._do_submit_job(job, run_times)
2023/11/23 00:21:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/23 00:21:00	stdout	    executor.submit_job(job, run_times)
2023/11/23 00:21:00	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/23 00:21:00	stdout	Traceback (most recent call last):
2023/11/23 00:21:00	stdout	Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-11-23 00:21:00 CST)" to executor "default"
2023/11/23 00:20:59	stdout	RuntimeError: cannot schedule new futures after shutdown
2023/11/23 00:20:59	stdout	    raise RuntimeError('cannot schedule new futures after shutdown')
2023/11/23 00:20:59	stdout	  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/11/23 00:20:59	stdout	    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/11/23 00:20:59	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/11/23 00:20:59	stdout	    self._do_submit_job(job, run_times)
2023/11/23 00:20:59	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/11/23 00:20:59	stdout	    executor.submit_job(job, run_times)
2023/11/23 00:20:59	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/11/23 00:20:59	stdout	Traceback (most recent call last):
2023/11/23 00:20:59	stdout	Error submitting job "SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-11-23 00:20:59 CST)" to executor "default"
2023/11/23 00:20:00	stdout	AttributeError: 'TORRENTREMOVETASK' object has no attribute 'ONLYNASTOOL'. Did you mean: 'ONLY_NASTOOL'?
2023/11/23 00:20:00	stdout	    "onlynastool": task.ONLYNASTOOL,
2023/11/23 00:20:00	stdout	  File "/nas-tools/app/torrentremover.py", line 56, in init_config
2023/11/23 00:20:00	stdout	    self.init_config()
2023/11/23 00:20:00	stdout	  File "/nas-tools/app/torrentremover.py", line 28, in __init__
2023/11/23 00:20:00	stdout	    INSTANCES[cls] = cls(*args, **kwargs)
2023/11/23 00:20:00	stdout	  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
2023/11/23 00:20:00	stdout	    TorrentRemover()
2023/11/23 00:20:00	stdout	  File "/nas-tools/web/action.py", line 336, in start_service
2023/11/23 00:20:00	stdout	    WebAction.start_service()
2023/11/23 00:20:00	stdout	  File "/nas-tools/run.py", line 105, in start_service
2023/11/23 00:20:00	stdout	    start_service()
2023/11/23 00:20:00	stdout	  File "/nas-tools/run.py", line 114, in <module>
2023/11/23 00:20:00	stdout	Traceback (most recent call last):
2023/11/23 00:20:00	stdout	2023-11-23 00:20:00,040 INFO: 1 个刷流服务正常启动
```

**Comment by hsuyelin** [comment]
新版本再试试
