### ISSUE TITLE
更新3.2.10.4死循环无法进入nastools

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#52]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 更新3.2.10.4之后一直循环报错，无法进入nastools

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 估计是改多站点浏览器仿真测试报错问题改出了bug，这个得修复才行了，不然我这直接无法启动，辛苦大佬看看了

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://github.com/hsuyelin/nas-tools/assets/64239067/1a1e2249-542e-4190-af4d-2f6f932b2bfb)
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/5ef20990-a32f-40fb-9e27-8d9d6fc4b698)

**Comment by TonyLiooo** [comment]
```
正在加载配置：/config/config.yaml
NAStool 当前版本号：v3.2.10.4
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
2023-08-15 01:14:24,772 INFO: 日志输出类型为：console
2023-08-15 01:14:24,772 INFO: WEB管理页面用户：
2023-08-15 01:14:24,772 INFO: 已启用https，请使用 https://IP: 访问管理页面
开始启动服务...
2023-08-15 01:14:24,954 INFO: 数据统计服务启动
Traceback (most recent call last):
  File "/nas-tools/run.py", line 115, in <module>
    start_service()
  File "/nas-tools/run.py", line 106, in start_service
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 336, in start_service
    Scheduler()
  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/scheduler.py", line 30, in __init__
    self.init_config()
  File "/nas-tools/app/scheduler.py", line 36, in init_config
    self.run_service()
  File "/nas-tools/app/scheduler.py", line 73, in run_service
    self.SCHEDULER.add_job(Rss().rssdownload, 'interval', seconds=pt_check_interval)
  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/rss.py", line 32, in __init__
    self.init_config()
  File "/nas-tools/app/rss.py", line 36, in init_config
    self.downloader = Downloader()
  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/downloader/downloader.py", line 53, in __init__
    self._downloader_schema = SubmoduleHelper.import_submodules(
  File "/nas-tools/app/helper/submodule_helper.py", line 22, in import_submodules
    module = importlib.import_module(full_package_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nas-tools/app/downloader/client/pikpak.py", line 3, in <module>
    from pikpakapi import PikPakApi, DownloadStatus
  File "/usr/local/lib/python3.10/site-packages/pikpakapi/__init__.py", line 3, in <module>
    import httpx
  File "/usr/local/lib/python3.10/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.10/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/usr/local/lib/python3.10/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/usr/local/lib/python3.10/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 14, in <module>
    from .http11 import HTTP11Connection
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 48, in <module>
    class HTTP11Connection(ConnectionInterface):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 149, in HTTP11Connection
    self, event: h11.Event, timeout: Optional[float] = None
AttributeError: module 'h11' has no attribute 'Event'
```

**Comment by TonyLiooo** [comment]
直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了

**Comment by hsuyelin** [comment]
> 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了

就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦

**Comment by hsuyelin** [comment]
> 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了

昨晚是测试的，可能有bug，早上更新了完整的版本重新拉下，重建一下试试看

**Comment by TonyLiooo** [comment]
> > 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了
> 
> 就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦

我觉得是还没来得及加锁就执行了下一个线程，可以考虑一下这样改试试
`def browser(self):
         if not self._chrome:
                with lock:
                    if not self._chrome:
                        self._chrome = self.__get_browser()
         return self._chrome`

**Comment by TonyLiooo** [comment]
> > 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了
> 
> 就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦

可以试试这样改，可能是执行下一个线程时候还来不及加锁
```
def browser(self):
    if not self._chrome:
        with lock:
            if not self._chrome:
                self._chrome = self.__get_browser()
    return self._chrome
```

**Comment by hsuyelin** [comment]
> > > 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了
> > 
> > 
> > 就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦
> 
> 可以试试这样改，可能是执行下一个线程时候还来不及加锁
> 
> ```
> def browser(self):
>     if not self._chrome:
>         with lock:
>             if not self._chrome:
>                 self._chrome = self.__get_browser()
>     return self._chrome
> ```

加锁就是为了避免并发问题，同时对 self._chrome 既读也写，这样写可能会触发一个线程在写（代码第五行），一个线程在读取 （代码第二行）结果更未可知，不改了吧

**Comment by TonyLiooo** [comment]
> > > > 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了
> > > 
> > > 
> > > 就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦
> > 
> > 
> > 可以试试这样改，可能是执行下一个线程时候还来不及加锁
> > ```
> > def browser(self):
> >     if not self._chrome:
> >         with lock:
> >             if not self._chrome:
> >                 self._chrome = self.__get_browser()
> >     return self._chrome
> > ```
> 
> 加锁就是为了避免并发问题，同时对 self._chrome 既读也写，这样写可能会触发一个线程在写（代码第五行），一个线程在读取 （代码第二行）结果更未可知，不改了吧

第一次if not self._chrome:是不是可以避免在不必要的情况下进入with lock:块呢，我不太确定，只是看了一部份源码。不过我刚刚试了下重新更新的，时间上也要好很多了，目前测试是可以用的

**Comment by hsuyelin** [comment]
> > > > > 直接重启更新会一直报错，重建之后可以正常，站点测试开启浏览器仿真可以测通，但是速度会非常慢，3秒时间可能会太长了
> > > > 
> > > > 
> > > > 就这样吧，源代码就加锁了都不能保证，深究就太费时间了，3秒就还好啦
> > > 
> > > 
> > > 可以试试这样改，可能是执行下一个线程时候还来不及加锁
> > > ```
> > > def browser(self):
> > >     if not self._chrome:
> > >         with lock:
> > >             if not self._chrome:
> > >                 self._chrome = self.__get_browser()
> > >     return self._chrome
> > > ```
> > 
> > 
> > 加锁就是为了避免并发问题，同时对 self._chrome 既读也写，这样写可能会触发一个线程在写（代码第五行），一个线程在读取 （代码第二行）结果更未可知，不改了吧
> 
> 第一次if not self._chrome:是不是可以避免在不必要的情况下进入with lock:块呢，我不太确定，只是看了一部份源码。不过我刚刚试了下重新更新的，时间上也要好很多了，目前测试是可以用的

多线程问题，这样解决不了的就用新更新的吧，有问题再说
