### ISSUE TITLE
[错误报告]: 从官方原版升级启动出错，如果部署的时候选择更新，启动后则显示没有run.py

### ISSUE THREAD

**Issue by werran2** [hsuyelin/nas-tools#522]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

latest

### 问题类型

主程序运行问题

### 问题描述

不断重新启动服务，显示如下方日志

如果部署的的时候选择更新，启动后则显示没有run.py

### 发生问题时系统日志和配置文件

```bash
Pending jobs:
    SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2024-01-10 03:22:57 CST)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2024-01-10 03:21:59 CST)
Traceback (most recent call last):
  File "/nas-tools/run.py", line 114, in <module>
    start_service()
  File "/nas-tools/run.py", line 105, in start_service
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 338, in start_service
    PluginManager()
  File "/nas-tools/app/utils/commons.py", line 23, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/plugins/plugin_manager.py", line 48, in __init__
    self.init_config()
  File "/nas-tools/app/plugins/plugin_manager.py", line 56, in init_config
    self.start_service()
  File "/nas-tools/app/plugins/plugin_manager.py", line 78, in start_service
    self.__load_plugins()
  File "/nas-tools/app/plugins/plugin_manager.py", line 102, in __load_plugins
    plugins = SubmoduleHelper.import_submodules(
  File "/nas-tools/app/helper/submodule_helper.py", line 22, in import_submodules
    module = importlib.import_module(full_package_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nas-tools/app/plugins/modules/jackett.py", line 5, in <module>
    from app.helper import IndexerConf
ImportError: cannot import name 'IndexerConf' from 'app.helper' (/nas-tools/app/helper/__init__.py)
```

**Comment by werran2** [comment]
最后重新部署，读取原版的备份文件恢复
