### ISSUE TITLE
[错误报告]: 自动删种任务：pt暂停做种异常：'Torrent' object has no attribute 'date_done'

### ISSUE THREAD

**Issue by panyuz** [hsuyelin/nas-tools#551]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.13 6c7b424

### 问题类型

主程序运行问题

### 问题描述

transmission 自动删种异常，提示无data_done属性。

### 发生问题时系统日志和配置文件

```bash
Exception: 'Torrent' object has no attribute 'date_done'
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/brushtask.py", line 357, in remove_tasks_torrents
    torrent_info = self.__get_torrent_dict(downloader_type=downloader_type,
  File "/nas-tools/app/brushtask.py", line 919, in __get_torrent_dict
    if not torrent.date_done or torrent.date_done.timestamp() < 1:
AttributeError: 'Torrent' object has no attribute 'date_done'
```

**Comment by hsuyelin** [comment]
已修复
