### ISSUE TITLE
[错误报告]: docker重启无法启动，出现错误代码

### ISSUE THREAD

**Issue by authon** [hsuyelin/nas-tools#574]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.14

### 问题类型

主程序运行问题

### 问题描述

docker启动后正常设置，一旦重启出现错误，错误代码如下

### 发生问题时系统日志和配置文件

```bash
OSError: [Errno 28] inotify watch limit reached
stderr
2024-02-25 22:45
raise OSError(errno.ENOSPC, "inotify watch limit reached")
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
stderr
2024-02-25 22:45
Inotify._raise_error()
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
stderr
2024-02-25 22:45
self._add_watch(path, mask)
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 395, in _add_dir_watch
stderr
2024-02-25 22:45
self._add_dir_watch(path, recursive, event_mask)
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
stderr
2024-02-25 22:45
self._inotify = Inotify(path, recursive)
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
stderr
2024-02-25 22:45
self._inotify = InotifyBuffer(path, self.watch.is_recursive)
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
stderr
2024-02-25 22:45
self.on_thread_start()
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
stderr
2024-02-25 22:45
emitter.start()
stderr
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/api.py", line 261, in start
stderr
2024-02-25 22:45
_observer.start()
stderr
2024-02-25 22:45
File "/nas-tools/initializer.py", line 418, in start_config_monitor
stderr
2024-02-25 22:45
start_config_monitor()
stderr
2024-02-25 22:45
File "/nas-tools/run.py", line 107, in start_service
stderr
2024-02-25 22:45
start_service()
stderr
2024-02-25 22:45
File "/nas-tools/run.py", line 114, in <module>
stderr
2024-02-25 22:45
Traceback (most recent call last):
stderr
2024-02-25 22:45
Wrong number of fields; got 6, expected 5
stdout
2024-02-25 22:45
Wrong number of fields; got 6, expected 5
stdout
2024-02-25 22:45
get_login_wallpaper (trigger: interval[1:00:00], next run at: 2024-02-25 22:45:53 CST)
stdout
2024-02-25 22:45
MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
stdout
2024-02-25 22:45
Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
stdout
2024-02-25 22:45
Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
stdout
2024-02-25 22:45
Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
stdout
2024-02-25 22:45
MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
stdout
2024-02-25 22:45
MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
stdout
2024-02-25 22:45
Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
stdout
2024-02-25 22:45
Rss.rssdownload (trigger: interval[0:30:00], pending)
stdout
2024-02-25 22:45
SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2024-02-25 22:46:51 CST)
stdout
2024-02-25 22:45
Pending jobs:
stdout
2024-02-25 22:45
stdout
2024-02-25 22:45
stdout
2024-02-25 22:45
OSError: [Errno 28] inotify watch limit reached
stdout
2024-02-25 22:45
raise OSError(errno.ENOSPC, "inotify watch limit reached")
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
stdout
2024-02-25 22:45
Inotify._raise_error()
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
stdout
2024-02-25 22:45
self._add_watch(full_path, mask)
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 402, in _add_dir_watch
stdout
2024-02-25 22:45
self._add_dir_watch(path, recursive, event_mask)
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
stdout
2024-02-25 22:45
self._inotify = Inotify(path, recursive)
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
stdout
2024-02-25 22:45
self._inotify = InotifyBuffer(path, self.watch.is_recursive)
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
stdout
2024-02-25 22:45
self.on_thread_start()
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
stdout
2024-02-25 22:45
emitter.start()
stdout
2024-02-25 22:45
File "/usr/local/lib/python3.10/site-packages/watchdog/observers/api.py", line 261, in start
stdout
2024-02-25 22:45
observer.start()
stdout
2024-02-25 22:45
File "/nas-tools/app/sync.py", line 345, in run_service
stdout
2024-02-25 22:45
Traceback (most recent call last):
stdout
2024-02-25 22:45
Callstack:
stdout
2024-02-25 22:45
Exception: [Errno 28] inotify watch limit reached
stdout
2024-02-25 22:45
stdout
2024-02-25 22:45
Downloader.transfer (trigger: interval[0:05:00], pending)
stdout
2024-02-25 22:45
Pending jobs:
stdout
2024-02-25 22:45
开始启动服务...
stdout
2024-02-25 22:45
数据初始化完成
stdout
2024-02-25 22:45
开始初始化数据...
stdout
2024-02-25 22:45
数据库更新完成
stdout
2024-02-25 22:45
开始更新数据库...
stdout
2024-02-25 22:45
数据库初始化完成
stdout
2024-02-25 22:45
开始初始化数据库...
stdout
2024-02-25 22:45
NAStool 当前版本号：v3.3.14
stdout
2024-02-25 22:45
正在加载flask环境变量: /nas-tools/.flaskenv
stdout
2024-02-25 22:45
正在加载配置：/config/config.yaml
```

**Comment by authon** [comment]
[OK](https://github.com/hsuyelin/nas-tools/issues/554)
