### ISSUE TITLE
RSS订阅日志打印报错

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#60]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.5 49bd606
>
> 环境: docker
>

## 你遇到什么问题了？

> 后台日志看到RSS订阅电视剧时候有报错信息，因为不是特意去使用的，不能确定错误原因

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有人提，看到了报错反馈一下

## 你期望的结果

> 大佬有空看看，能解决最好，毕竟我不怎么用上，但是可能会有其他人用的上

## 给出程序界面截图、后台运行日志或配置文件
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/23e4228d-0e98-40b3-aae5-f1910b599cbf)

> 如UI BUG请提供截图及配置文件截图
```
2023-08-17 19:26:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 19:26:26,507 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 19:26:26,782 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 19:56:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 19:56:26,558 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 19:56:26,783 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 20:26:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 20:26:26,587 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 20:26:26,910 WARNING: 【Rss】没有正在订阅的电视剧
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2197, in wsgi_app
    return response(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask_sock/__init__.py", line 86, in __call__
    raise ConnectionError()
ConnectionError
2023-08-17 20:56:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 20:56:26,703 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 20:56:26,927 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 21:26:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 21:26:26,570 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 21:26:26,843 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 21:56:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 21:56:26,463 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 21:56:26,811 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 22:26:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 22:26:26,567 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 22:26:26,875 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 22:56:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 22:56:26,542 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 22:56:26,794 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 23:26:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 23:26:26,539 WARNING: 【Rss】没有正在订阅的电影
2023-08-17 23:26:26,770 WARNING: 【Rss】没有正在订阅的电视剧
2023-08-17 23:56:26,202 INFO: 【Rss】开始RSS订阅...
2023-08-17 23:56:26,539 WARNING: 【Rss】没有正在订阅的电影
```

**Comment by hsuyelin** [comment]
这个报错不影响，是socket暂时断开了，和即时日志显示有关系，和RSS关系不大，一会连上就好了
