### ISSUE TITLE
[错误报告]: MT输入cookie和令牌或删除cookie只留令牌 测试网站都是无法打开 

### ISSUE THREAD

**Issue by Lollipop520** [hsuyelin/nas-tools#655]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.4.0 f93cd9a

### 问题类型

主程序运行问题

### 问题描述

MT输入cookie和令牌或删除cookie只留令牌 测试网站都是无法打开 

### 发生问题时系统日志和配置文件

```bash
获取馒头系统角色失败，无法连接 https://kp.m-team.cc/api/member/sysRoleList
16:59:14		
获取馒头用户属性失败，无法连接 https://kp.m-team.cc/api/member/profile
16:59:14		
站点 M-Team 获取流量数据失败：'NoneType' object has no attribute 'get'
```

**Comment by joneechua** [comment]
更新最新代码，看看日志

**Comment by Lollipop520** [comment]
> 更新最新代码，看看日志

更新代码解决 谢谢

**Comment by githejian** [comment]
V3.4.0
21:19:27 | MTeamUserInfo | 获取馒头系统角色失败，无法连接 https://kp.m-team.cc/api/member/sysRoleList
21:19:58 | MTeamUserInfo | 获取馒头用户属性失败，无法连接 https://kp.m-team.cc/api/member/profile

怎么更新代码解决 大佬教教我

**Comment by joneechua** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/156154680/7fcc3796-16cf-4793-a492-f7353ce24730)

**Comment by NicholasYZ** [comment]
使用docker部署，image id `sha256:af9f13c092a8f1926b404bcc9c334b` 创建时间 2024-04-17 20:30:16，并更新代码，无法获取数据，更新代码之后的日志：
```
 获取流量数据失败：'bool' object has no attribute 'get' - Traceback (most recent call last):
  File "/nas-tools/app/sites/site_userinfo.py", line 206, in __refresh_site_data
    site_user_info.parse()
  File "/nas-tools/app/sites/siteuserinfo/_base.py", line 123, in parse
    self._parse_user_base_info(self._index_html)
  File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 141, in _parse_user_base_info
    self._mt_get_sys_roles()
  File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 56, in _mt_get_sys_roles
    res = RequestUtils(
  File "/nas-tools/app/utils/http_utils.py", line 141, in post_res
    return requests.post(url,
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 579, in request
    settings = self.merge_environment_settings(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 760, in merge_environment_settings
    no_proxy = proxies.get("no_proxy") if proxies is not None else None
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by joneechua** [comment]
> 使用docker部署，image id `sha256:af9f13c092a8f1926b404bcc9c334b` 创建时间 2024-04-17 20:30:16，并更新代码，无法获取数据，更新代码之后的日志：
> 
> ```
>  获取流量数据失败：'bool' object has no attribute 'get' - Traceback (most recent call last):
>   File "/nas-tools/app/sites/site_userinfo.py", line 206, in __refresh_site_data
>     site_user_info.parse()
>   File "/nas-tools/app/sites/siteuserinfo/_base.py", line 123, in parse
>     self._parse_user_base_info(self._index_html)
>   File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 141, in _parse_user_base_info
>     self._mt_get_sys_roles()
>   File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 56, in _mt_get_sys_roles
>     res = RequestUtils(
>   File "/nas-tools/app/utils/http_utils.py", line 141, in post_res
>     return requests.post(url,
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
>     return request("post", url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 579, in request
>     settings = self.merge_environment_settings(
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 760, in merge_environment_settings
>     no_proxy = proxies.get("no_proxy") if proxies is not None else None
> AttributeError: 'bool' object has no attribute 'get'
> ```

等PR合入

**Comment by joneechua** [comment]
> 使用docker部署，image id `sha256:af9f13c092a8f1926b404bcc9c334b` 创建时间 2024-04-17 20:30:16，并更新代码，无法获取数据，更新代码之后的日志：
> ```
>  获取流量数据失败：'bool' object has no attribute 'get' - Traceback (most recent call last):
>   File "/nas-tools/app/sites/site_userinfo.py", line 206, in __refresh_site_data
>     site_user_info.parse()
>   File "/nas-tools/app/sites/siteuserinfo/_base.py", line 123, in parse
>     self._parse_user_base_info(self._index_html)
>   File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 141, in _parse_user_base_info
>     self._mt_get_sys_roles()
>   File "/nas-tools/app/sites/siteuserinfo/mteam_torrent.py", line 56, in _mt_get_sys_roles
>     res = RequestUtils(
>   File "/nas-tools/app/utils/http_utils.py", line 141, in post_res
>     return requests.post(url,
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
>     return request("post", url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 579, in request
>     settings = self.merge_environment_settings(
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 760, in merge_environment_settings
>     no_proxy = proxies.get("no_proxy") if proxies is not None else None
> AttributeError: 'bool' object has no attribute 'get'
> ```

更新了

**Comment by NicholasYZ** [comment]
依然不通，使用了代理（不用会显示找不到网站），删除了cookie，使用apikey，域名为https://kp.m-team.cc，日志：
```
WARNING: 【MTeamUserInfo】 获取馒头系统角色失败，错误码：404
WARNING: 【MTeamUserInfo】 获取馒头用户属性失败，错误码：404
```

**Comment by joneechua** [comment]
换xp.m-team.io试试？

**Comment by NicholasYZ** [comment]
换了xp.m-team.io还是一样，代理大概是没有问题的，U2套上代理之后是能联通的，mt的我试着（在nastool和代理之间）抓包，似乎是建立连接了
但是nastool还是显示404
![图片](https://github.com/hsuyelin/nas-tools/assets/46787434/0e0aa876-61d5-44d4-b4ed-0e39b20870e6)

**Comment by jianqiao0313** [comment]
+1，更新代码也不好使。
实时日志显示无法连接，但是用浏览器访问是可以访问的，也没有挂代理。
<img width="533" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/15814955/164cd4eb-1eb5-4045-8b0e-a5897b11e7b3">

**Comment by jianqiao0313** [comment]
> 用ssh登陆nas尝试curl一下url看看通不通，看着是nas的网络问题

![image](https://github.com/hsuyelin/nas-tools/assets/15814955/93c29c22-1c63-445e-99b9-0d91f2ac86ac)

我用curl和wget都正常啊。。。

**Comment by joneechua** [comment]
docker部署的吗？docker里面试试呢？

**Comment by jianqiao0313** [comment]
是docker部署。上图用的是docker里面的ssh访问的。
另外，我尝试了部署firefox的docker镜像，访问这个域名，也是可以正常打开登录的，没挂代理。。。

**Comment by joneechua** [comment]
不知道了，只能上机调试了，哈哈

**Comment by harmony626** [comment]
完全一样的问题，但是更新还是没解决。请问有人解决了吗？apikey是填上就可以吧？

**Comment by joneechua** [comment]
看看馒头配置，需要配置ua+apikey

**Comment by jianqiao0313** [comment]
我加上UA和APIkey后，就可以使用了~

**Comment by jianqiao0313** [comment]
> > > 看看馒头配置，需要配置ua+apikey
> > 
> > 
> > 我加上UA和APIkey后，就可以使用了~ 感谢大佬~
> 
> UA用的是哪个 可以参考一下吗

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
我用的这个，其他配置如下，未翻墙，未代理，用的家里的宽带，可以正常访问：
![image](https://github.com/hsuyelin/nas-tools/assets/15814955/09658114-687f-437e-b42b-898e579ef691)

**Comment by joneechua** [comment]
大家在贴图片、日志的时候把mt的域名都隐藏掉，不要因为我们的工具导致域名被ban，到时候我们上黑名单就不好了

**Comment by jianqiao0313** [comment]
好的，已把网址打码，感谢提醒~
