### ISSUE TITLE
[错误报告]: 添加下载器Aria2测试连接失败

### ISSUE THREAD

**Issue by liangyoufeng** [hsuyelin/nas-tools#761]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.1

### 问题类型

主程序运行问题

### 问题描述

测试失败如下：
![bug1](https://github.com/user-attachments/assets/02e0eecb-dbbd-47e7-82e6-8a6c923774a0)

下载失败如下
![bug2](https://github.com/user-attachments/assets/ba0258c6-53d0-4744-ae24-2786905f72ba)

使用的是索引器是Jackett，我看索引器并没有Jackett配置就载插件中心安装了然后配置上去。qb是正常的
访问自己的air2是正常的
![bug3](https://github.com/user-attachments/assets/ae10a394-640c-4995-8cfc-ede3bfec9d85)

### 发生问题时系统日志和配置文件

```bash
在web端点击下载，发现报错日志如下：
2024-07-25 10:28:56,661 INFO: 【Meta】正在查询TMDB电视剧：248947 ...
2024-07-25 10:28:56,662 INFO: 【Meta】248947 查询结果：妖精的尾巴 百年任务
2024-07-25 10:28:56,670 INFO: 【Downloader】下载器 Aria2 添加任务：[NeoLX] Fairy Tail - 100 Years Quest (100年クエスト) - S01E01 [Mod][1080p x264 10bits AAC][Multiple Subtitles].mkv，目录：None，Url：magnet:?xt=urn:btih:E5629C6949DAC995AFE80D7AA07FA1DC106AB43C
2024-07-25 10:28:56,671 INFO: 处理事件：download.add - [<function DownloaderHelper.listen_download_add_event at 0x73aff4c14b80>, <function Webhook.send at 0x73aff4c06050>]

Exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Callstack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1104, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 269, in action
    return func(data)
  File "/nas-tools/web/action.py", line 5089, in __test_downloader
    res = Downloader().get_status(dtype=dtype, config=config)
  File "/nas-tools/app/downloader/downloader.py", line 1380, in get_status
    state = download_client.get_status() if download_client else False
  File "/nas-tools/app/downloader/client/aria2.py", line 56, in get_status
    ver = self._client.getVersion()
  File "/nas-tools/app/downloader/client/_pyaria2.py", line 377, in getVersion
    return self._send_request("aria2.getVersion")
  File "/nas-tools/app/downloader/client/_pyaria2.py", line 51, in _send_request
    response = requests.post(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))


2024-07-25 10:29:26,703 ERROR: 【Downloader】下载器 Aria2 添加任务出错：('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-07-25 10:29:26,704 INFO: 处理事件：download.fail - [<function Webhook.send at 0x73aff4c06050>]
```

**Comment by endless1651** [comment]
端口是不是填错了，6800填写成了6880

**Comment by liangyoufeng** [comment]
感谢！是我疏忽了，我一直以为调用的是web端口，功能使用正常。
