### ISSUE TITLE
添加下载失败 startswith first arg must be bytes or a tuple of bytes, not str无法从nastool添加下载

### ISSUE THREAD

**Issue by aztdmxb** [hsuyelin/nas-tools#786]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.1

### 问题类型

主程序运行问题

### 问题描述

添加下载失败 startswith first arg must be bytes or a tuple of bytes, not str
![QQ20241006-180801](https://github.com/user-attachments/assets/daa0b593-09eb-46fb-8743-7e00c521dc4e)
处理事件：download.add - [<function DownloaderHelper.listen_download_add_event at 0x7f26d050a4d0>, <function Webhook.send at 0x7f26d05039a0>]

![QQ20241006-181216](https://github.com/user-attachments/assets/b8eb5ca1-0a36-4bb3-bdde-2059817e2dec)

### 发生问题时系统日志和配置文件

```bash
Exception: startswith first arg must be bytes or a tuple of bytes, not str
Callstack:
Traceback (most recent call last):
File "/nas-tools/web/main.py", line 1104, in do
return WebAction().action(cmd, data)
File "/nas-tools/web/action.py", line 269, in action
return func(data)
2024-10-06 18:06:55,220 INFO: 处理事件：download.add - [<function DownloaderHelper.listen_download_add_event at 0x7f468ba20280>, <function Webhook.send at 0x7f468ba65d80>]
File "/nas-tools/web/action.py", line 625, in __download_link
_, ret, ret_msg = Downloader().download(media_info=media,
File "/nas-tools/app/downloader/downloader.py", line 333, in download
if url.startswith("magnet:"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str



Exception: startswith first arg must be bytes or a tuple of bytes, not str
Callstack:
Traceback (most recent call last):
File "/nas-tools/web/main.py", line 1104, in do
return WebAction().action(cmd, data)
File "/nas-tools/web/action.py", line 269, in action
return func(data)
File "/nas-tools/web/action.py", line 625, in __download_link
_, ret, ret_msg = Downloader().download(media_info=media,
File "/nas-tools/app/downloader/downloader.py", line 333, in download
if url.startswith("magnet:"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by naughtyGitCat** [comment]
fixed   in https://github.com/naughtyGitCat/nas-tools,  u can try it

**Comment by XXwhite** [comment]
兄弟我找到了解决办法，我使用馒头要到了同样的问题，在站点维护中新增一个站点，地址是https://api.m-team.cc，其他保持不变，这样就能正常下载了。

**Comment by LukeLu0415** [comment]
> 兄弟我找到了解决办法，我使用馒头要到了同样的问题，在站点维护中新增一个站点，地址是[https://api.m-team.cc，其他保持不变，这样就能正常下载了。](https://api.m-team.cc%EF%BC%8C%E5%85%B6%E4%BB%96%E4%BF%9D%E6%8C%81%E4%B8%8D%E5%8F%98%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%B1%E8%83%BD%E6%AD%A3%E5%B8%B8%E4%B8%8B%E8%BD%BD%E4%BA%86%E3%80%82)

牛逼啊，什么原理呢

**Comment by XXwhite** [comment]
> > 兄弟我找到了解决办法，我使用馒头要到了同样的问题，在站点维护中新增一个站点，地址是[https://api.m-team.cc，其他保持不变，这样就能正常下载了。](https://api.m-team.cc%EF%BC%8C%E5%85%B6%E4%BB%96%E4%BF%9D%E6%8C%81%E4%B8%8D%E5%8F%98%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%B1%E8%83%BD%E6%AD%A3%E5%B8%B8%E4%B8%8B%E8%BD%BD%E4%BA%86%E3%80%82)
> 
> 牛逼啊，什么原理呢

可能因为馒头种子的地址跟网站地址前缀不一样导致nastool识别错误吧
