### ISSUE TITLE
[错误报告]: 首页无法获取豆瓣API信息

### ISSUE THREAD

**Issue by jaychoww** [hsuyelin/nas-tools#803]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.4.1 3f13575

### 问题类型

主程序运行问题

### 问题描述

首页的榜单推荐, 豆瓣电影, 豆瓣电视都无法显示

### 发生问题时系统日志和配置文件

```bash
Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/tv_chinese_best_weekly/items
Callstack:
Traceback (most recent call last):
  File "/volume1/@appstore/NASTool/nas-tools/web/main.py", line 1104, in do
    return WebAction().action(cmd, data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 269, in action
    return func(data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 2372, in get_recommend
    res_list = DouBan().get_douban_chinese_weekly_tv(CurrentPage)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/douban.py", line 365, in get_douban_chinese_weekly_tv
    infos = self.doubanapi.tv_chinese_best_weekly(start=(page - 1) * self._tv_num,
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 292, in tv_chinese_best_weekly
    return self.__invoke_ttl(self._urls["tv_chinese_best_weekly"], start=start, count=count, _ts=ts)
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 83, in wrapper
    raise e
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 77, in wrapper
    result = func(*args, **kwargs)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 226, in __invoke_ttl
    raise Exception("cannot invoke %s" % req_url)
Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/tv_chinese_best_weekly/items



Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/movie_soon/items
Callstack:
Traceback (most recent call last):
  File "/volume1/@appstore/NASTool/nas-tools/web/main.py", line 1104, in do
    return WebAction().action(cmd, data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 269, in action
    return func(data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 2363, in get_recommend
    res_list = DouBan().get_douban_new_movie(CurrentPage)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/douban.py", line 338, in get_douban_new_movie
    infos = self.doubanapi.movie_soon(start=(page - 1) * self._movie_num,
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 247, in movie_soon
    return self.__invoke_ttl(self._urls["movie_soon"], start=start, count=count, _ts=ts)
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 83, in wrapper
    raise e
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 77, in wrapper
    result = func(*args, **kwargs)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 226, in __invoke_ttl
    raise Exception("cannot invoke %s" % req_url)
Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/movie_soon/items



Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/movie_showing/items
Callstack:
Traceback (most recent call last):
  File "/volume1/@appstore/NASTool/nas-tools/web/main.py", line 1104, in do
    return WebAction().action(cmd, data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 269, in action
    return func(data)
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 2351, in get_recommend
    res_list = DouBan().get_douban_online_movie(CurrentPage)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/douban.py", line 302, in get_douban_online_movie
    infos = self.doubanapi.movie_showing(start=(page - 1) * self._movie_num,
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 244, in movie_showing
    return self.__invoke_ttl(self._urls["movie_showing"], start=start, count=count, _ts=ts)
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 83, in wrapper
    raise e
  File "/volume1/@appstore/NASTool/nas-tools/app/utils/commons.py", line 77, in wrapper
    result = func(*args, **kwargs)
  File "/volume1/@appstore/NASTool/nas-tools/app/media/doubanapi/apiv2.py", line 226, in __invoke_ttl
    raise Exception("cannot invoke %s" % req_url)
Exception: cannot invoke https://frodo.douban.com/api/v2/subject_collection/movie_showing/items
```

**Comment by jaychoww** [comment]
目测是默认内置的API KEY被封了

**Comment by jaychoww** [comment]
我的网络问题, 不知道为啥访问不了douban.com
